#ifndef PRETTYNAMER_H
#define PRETTYNAMER_H

#include <QDataStream>
#include <QFile>
#include <QString>
#include <unordered_map>

class PrettyNamer
{
    public:
        const std::unordered_map<QString, QString> &getPrettyMap(const QByteArray &md5Hash);

    private:
        const std::unordered_map<QString, QString> emptyMap {};
        const std::unordered_map<QString, QString> kfUSPrettyMap{
            {"FDAT.T0", "Western Shore Tilemap"},
            {"FDAT.T1", "Western Shore Map DB"},
            {"FDAT.T2", "Western Shore Script"},
            {"FDAT.T3", "Garrison Tilemap"},
            {"FDAT.T4", "Garrison Map DB"},
            {"FDAT.T5", "Garrison Script"},
            {"FDAT.T6", "Central Village Tilemap"},
            {"FDAT.T7", "Central Village Map DB"},
            {"FDAT.T8", "Central Village Script"},
            {"FDAT.T9", "East Village Tilemap"},
            {"FDAT.T10", "East Village Map DB"},
            {"FDAT.T11", "East Village Script"},
            {"FDAT.T12", "Cathedral Tilemap"},
            {"FDAT.T13", "Cathedral Map DB"},
            {"FDAT.T14", "Cathedral Script"},
            {"FDAT.T15", "Big Mine Tilemap"},
            {"FDAT.T16", "Big Mine Map DB"},
            {"FDAT.T17", "Big Mine Script"},
            {"FDAT.T18", "Necron's Coliseum Tilemap"},
            {"FDAT.T19", "Necron's Coliseum Map DB"},
            {"FDAT.T20", "Necron's Coliseum Script"},
            {"FDAT.T21", "Guyra's Lair Tilemap"},
            {"FDAT.T22", "Guyra's Lair Map DB"},
            {"FDAT.T23", "Guyra's Lair Script"},
            {"FDAT.T24", "Weird Debug Map Tilemap"},
            {"FDAT.T25", "Weird Debug Map Map DB"},
            {"FDAT.T26", "Weird Debug Map Script"},
            {"FDAT.T27", "Texture Database"},
            {"FDAT.T28", "Game Database"},
            {"FDAT.T29", "Dagger Viewmodel"},
            {"FDAT.T30", "Short Sword Viewmodel"},
            {"FDAT.T31", "Knight Sword Viewmodel"},
            {"FDAT.T32", "Morning Star Viewmodel"},
            {"FDAT.T33", "Battle Hammer Viewmodel"},
            {"FDAT.T34", "Bastard Sword Viewmodel"},
            {"FDAT.T35", "Crescent Axe Viewmodel"},
            {"FDAT.T36", "Flame Sword Viewmodel"},
            {"FDAT.T37", "Shiden Viewmodel"},
            {"FDAT.T38", "Spider Viewmodel"},
            {"FDAT.T39", "Ice Blade Viewmodel"},
            {"FDAT.T40", "Seath's Sword Viewmodel"},
            {"FDAT.T41", "Moonlight Sword Viewmodel"},
            {"FDAT.T42", "Dark Slayer Viewmodel"},
            {"FDAT.T43", "Bow Viewmodel"},
            {"FDAT.T44", "Arbalest Viewmodel"},

            {"ITEM.T0", "Dagger Model"},
            {"ITEM.T1", "Short Sword Model"},
            {"ITEM.T2", "Knight Sword Model"},
            {"ITEM.T3", "Morning Star Model"},
            {"ITEM.T4", "Battle Hammer Model"},
            {"ITEM.T5", "Bastard Sword Model"},
            {"ITEM.T6", "Crescent Axe Model"},
            {"ITEM.T7", "Flame Sword Model"},
            {"ITEM.T8", "Shiden Model"},
            {"ITEM.T9", "Spider Model"},
            {"ITEM.T10", "Ice Blade Model"},
            {"ITEM.T11", "Seath's Sword Model"},
            {"ITEM.T12", "Moonlight Sword Model"},
            {"ITEM.T13", "Dark Slayer Model"},
            {"ITEM.T14", "Bow Model"},
            {"ITEM.T15", "Arbalest Model"},
            {"ITEM.T16", "Iron Mask Model"},
            {"ITEM.T17", "Knight Helm Model"},
            {"ITEM.T18", "Great Helm Model"},
            {"ITEM.T19", "Blood Crown Model"},
            {"ITEM.T20", "Lightning Helm Model"},
            {"ITEM.T21", "Seath's Helm Model"},
            {"ITEM.T22", "Breast Plate Model"},
            {"ITEM.T23", "Knight Plate Model"},
            {"ITEM.T24", "Ice Armor Model"},
            {"ITEM.T25", "Dark Armor Model"},
            {"ITEM.T26", "Seath's Armor Model"},
            {"ITEM.T27", "Leather Shield Model"},
            {"ITEM.T28", "Large Shield Model"},
            {"ITEM.T29", "Moon Guard Model"},
            {"ITEM.T30", "Crystal Guard Model"},
            {"ITEM.T31", "Skull Shield Model"},
            {"ITEM.T32", "Seath's Shield Model"},
            {"ITEM.T33", "Iron Gloves Model"},
            {"ITEM.T34", "Stone Hands Model"},
            {"ITEM.T35", "Silver Arms Model"},
            {"ITEM.T36", "Demon's Hands Model"},
            {"ITEM.T37", "Ruinous Gloves Model"},
            {"ITEM.T38", "Iron Boots Model"},
            {"ITEM.T39", "Leg Guarders Model"},
            {"ITEM.T40", "Silver Boots Model"},
            {"ITEM.T41", "Death Walkers Model"},
            {"ITEM.T42", "Ruinous Boots Model"},
            {"ITEM.T43", "Scorpion's Bracelet Model"},
            {"ITEM.T44", "Seath's Tear Model"},
            {"ITEM.T45", "Seath's Bracelet Model"},
            {"ITEM.T46", "Earth Ring Model"},
            {"ITEM.T47", "Psycpros Collar Model"},
            {"ITEM.T48", "Amulet Of Mist Model"},
            {"ITEM.T49", "Lightwave Ring Model"},
            {"ITEM.T50", "Pirate's Map Model"},
            {"ITEM.T51", "Miner's Map Model"},
            {"ITEM.T52", "Necron's Map Model"},
            {"ITEM.T53", "Gold Coin Model"},
            {"ITEM.T54", "Blood Stone Model"},
            {"ITEM.T55", "Moon Stone Model"},
            {"ITEM.T56", "Verdite Model"},
            {"ITEM.T57", "Earth Herb Model"},
            {"ITEM.T58", "Antidote Model"},
            {"ITEM.T59", "Dragon Crystal Model"},
            {"ITEM.T60", "Blue Potion Model"},
            {"ITEM.T61", "Red Potion Model"},
            {"ITEM.T62", "Green Potion Model"},
            {"ITEM.T63", "Gold Potion Model"},
            {"ITEM.T64", "\"A\" Potion Model"},
            {"ITEM.T65", "Crystal Flask Model"},
            {"ITEM.T66", "Figure Of Seath Model"},
            {"ITEM.T67", "Phantom Rod Model"},
            {"ITEM.T68", "Truth Glass Model"},
            {"ITEM.T69", "Seath's Plume Model"},
            {"ITEM.T70", "Demon's Pick Model"},
            {"ITEM.T71", "Harvine's Flute Model"},
            {"ITEM.T72", "Ground Bell Model"},
            {"ITEM.T73", "Fire Crystal Model"},
            {"ITEM.T74", "Water Crystal Model"},
            {"ITEM.T75", "Earth Crystal Model"},
            {"ITEM.T76", "Wind Crystal Model"},
            {"ITEM.T77", "Light Crystal Model"},
            {"ITEM.T78", "Dark Crystal Model"},
            {"ITEM.T79", "Crystal Model"},
            {"ITEM.T80", "Crystal Shard Model"},
            {"ITEM.T81", "\"A\" Ring Model"},
            {"ITEM.T82", "Elf's Key Model"},
            {"ITEM.T83", "Pirate's Key Model"},
            {"ITEM.T84", "Skull Key Model"},
            {"ITEM.T85", "Jail Key Model"},
            {"ITEM.T86", "Rhombus Key Model"},
            {"ITEM.T87", "Harvine's Key Model"},
            {"ITEM.T88", "Dragon Stone Model"},
            {"ITEM.T89", "Magician's Key Model"},
            {"ITEM.T90", "Silver Key Model"},
            {"ITEM.T91", "Gold Key Model"},
            {"ITEM.T92", "Shrine Key Model"},
            {"ITEM.T93", "\"A\" Herb Model"},
            {"ITEM.T94", "Moon Gate Model"},
            {"ITEM.T95", "Star Gate Model"},
            {"ITEM.T96", "Sun Gate Model"},
            {"ITEM.T97", "Moon Key Model"},
            {"ITEM.T98", "Star Key Model"},
            {"ITEM.T99", "Sun Key Model"},
            {"ITEM.T100", "Arrow For The Bow Model"},
            {"ITEM.T101", "Elf's Bolt Model"},
            {"ITEM.T102", "\"A\" Herb 2 Model"},
            {"ITEM.T103", "Text: Al Hunt"},
            {"ITEM.T104", "Text: Nola Bagil"},
            {"ITEM.T105", "Text: Mark Wozz"},
            {"ITEM.T106", "Text: Rand Ferrer"},
            {"ITEM.T107", "Text: Radd Bilheim"},
            {"ITEM.T108", "Text: Kehl Hunt"},
            {"ITEM.T109", "Text: Krola Sandler Amgun"},
            {"ITEM.T110", "Text: Cliff Lore"},
            {"ITEM.T111", "Text: David Tabler"},
            {"ITEM.T112", "Text: Dalf Vice"},
            {"ITEM.T113", "Text: Harris Carvitto"},
            {"ITEM.T114", "Text: Teo Gigi Budwell"},
            {"ITEM.T115", "Text: Karen Leon Shore"},
            {"ITEM.T116", "Text: Base No1"},
            {"ITEM.T117", "Text: Base No2"},
            {"ITEM.T118", "Text: Base No3"},
            {"ITEM.T119", "Text: Base No4"},
            {"ITEM.T120", "Text: Base No5"},
            {"ITEM.T121", "Text: Base No6"},
            {"ITEM.T122", "Text: The Magic Cave Of Ice"},
            {"ITEM.T123", "Text: Base No7"},
            {"ITEM.T124", "Text: The Entrance To The North Village"},
            {"ITEM.T125", "Text: The Entrance To The South Village"},
            {"ITEM.T126", "Text: The Space For Completion No Trespassing"},
            {"ITEM.T127", "Text: The Entrance To The Central Village"},
            {"ITEM.T128", "Text: The Entrance To The Big Mine"},
            {"ITEM.T129", "Text: The Underworld Prison No1"},
            {"ITEM.T130", "Text: The Underworld Prison No2"},
            {"ITEM.T131", "Text: The Cemetery For The Military Guards Of King Harvine III"},
            {"ITEM.T132", "Text: Royal Treasure House"},
            {"ITEM.T133", "Text: The Magic Cave Of Fire"},
            {"ITEM.T134", "Text: Warriors Who Were Killed By Guyras Legion Are Buried Here"},
            {"ITEM.T135",
             "Text: The Souls Of The Guards Who Were Killed Are Waiting To Watch The Next Fight"},
            {"ITEM.T136",
             "Text: The King Of Winds King Harvine IIIHad Started To Construct His Castle Here"},
            {"ITEM.T137",
             "Text: The Castle Of The Great Ruler Of The Northern Continent King Harvine III"},
            {"ITEM.T138", "Text: Danger Ahead"},
            {"ITEM.T139",
             "Text: In The Name Of The Great Mage No One Can Enter This Cave Of Earth Soul"},
            {"ITEM.T140",
             "Text: Galth Free The Demon Of The Darkside Died With The High Elves He Is APhantom "
             "Of The World"},
            {"ITEM.T141", "Text: AMessage From The East Land Rest In Peace Here"},
            {"ITEM.T142",
             "Text: Most Soldiers Have Already Died There Is No Way To Leave The Island We Realize "
             "That There Is No Way Back Home"},
            {"ITEM.T143",
             "Text: In The Name Of Tsedeck The Mage Of Fire Who Defeated King Harvine IIIAnd Ruled "
             "The Northern Continent"},
            {"ITEM.T144", "Text: Gigis House Sandler"},
            {"ITEM.T145", "Text: They Can Be Attacked By Bows Take Good Aim"},
            {"ITEM.T146", "Text: Do Not Enter Old Hand"},
            {"ITEM.T147", "Text: Medical Herbs For Sale Al Hunt"},
            {"ITEM.T148", "Text: The South Graveyard To The Small Mine"},
            {"ITEM.T149", "Text: Termites Nest Ahead Watch Your Step"},
            {"ITEM.T150",
             "Text: My Beloved Son You Have Fought For Me And Have Lost Your Life For Me May You "
             "Rest In Peace"},
            {"ITEM.T151", "Text: Do Not Get Closer Krakens Nest"},
            {"ITEM.T152", "Text: Dangerous No Exit"},
            {"ITEM.T153", "Text: The Elf Cave"},
            {"ITEM.T154",
             "Text: By And By AMan Who Comes Here Beats The Black Dragon With The Blessing Of "
             "Seath"},
            {"ITEM.T155", "Text: The Cave Of The Darkside This Is Hell"},
            {"ITEM.T156", "Text: Offer Everything To Guyra Who Rules The Light And The Dark"},
            {"ITEM.T157", "Text: They Are Creating Devils Be Careful"},
            {"ITEM.T158", "Text: When The Warriors Stand Up The Great Door Will Be Opened Again"},
            {"ITEM.T159", "Text: The Entrance To The Small Mine"},
            {"ITEM.T160", "Text: The Poisoned Cave Dangerous"},
            {"ITEM.T161", "Text: The Great Demon's Grave"},
            {"ITEM.T162", "Text: Earnests Body"},
            {"ITEM.T163", "Text: The Picture Of Warriors"},
            {"ITEM.T164", "Text: Truth Glass Green Slime"},
            {"ITEM.T165", "Text: Truth Glass Poison Slime"},
            {"ITEM.T166", "Text: Truth Glass Sigill"},
            {"ITEM.T167", "Text: Truth Glass Sigill 2"},
            {"ITEM.T168", "Text: Truth Glass Baltail"},
            {"ITEM.T169", "Text: Truth Glass Baltail 2"},
            {"ITEM.T170", "Text: Truth Glass Poison Baltail"},
            {"ITEM.T171", "Text: Truth Glass Poison Baltail 2"},
            {"ITEM.T172", "Text: Truth Glass Fire Elemental"},
            {"ITEM.T173", "Text: Truth Glass Fire Elemental 2"},
            {"ITEM.T174", "Text: Truth Glass Ghosts"},
            {"ITEM.T175", "Text: Truth Glass Reiks"},
            {"ITEM.T176", "Text: Truth Glass Head Eater"},
            {"ITEM.T177", "Text: Truth Glass Mogle"},
            {"ITEM.T178", "Text: Truth Glass S-Knight"},
            {"ITEM.T179", "Text: Truth Glass Necron's Soldiers"},
            {"ITEM.T180", "Text: Truth Glass Archers"},
            {"ITEM.T181", "Text: Truth Glass Skeleton"},
            {"ITEM.T182", "Text: Truth Glass Termite"},
            {"ITEM.T183", "Text: Truth Glass Kald"},
            {"ITEM.T184", "Text: Truth Glass Psythe"},
            {"ITEM.T185", "Text: Truth Glass Queen Termite"},
            {"ITEM.T186", "Text: Truth Glass Freeze Ball"},
            {"ITEM.T187", "Text: Truth Glass Log Stalker"},
            {"ITEM.T188", "Text: Truth Glass Demon Lord"},
            {"ITEM.T189", "Text: Truth Glass Kraken"},
            {"ITEM.T190", "Text: Truth Glass Kraken 2"},
            {"ITEM.T191", "Text: Truth Glass Earth Elemental"},
            {"ITEM.T192", "Text: Truth Glass Refma"},
            {"ITEM.T193", "Text: Truth Glass Tarn"},
            {"ITEM.T194", "Text: Truth Glass Copper Knight"},
            {"ITEM.T195", "Text: Truth Glass Dias Bagil"},
            {"ITEM.T196", "Text: Truth Glass Guyra"},
            {"ITEM.T197", "Text: Truth Glass Salamander"},
            {"ITEM.T198", "Text: Truth Glass Flame Spirit"},
            {"ITEM.T199", "Text: Truth Glass Billent"},
            {"ITEM.T200", "Text: Truth Glass Skeleton Of One Eyed Giant"},
            {"ITEM.T201", "Text: Truth Glass The Picture Of A King"},
            {"ITEM.T201", "Text: Truth Glass The Picture Of A King"},
            {"ITEM.T202", "Text: Truth Glass Mecha Demon Lord"},
            {"ITEM.T203", "Text: Truth Glass Mecha Termite"},
            {"ITEM.T204", "Text: Truth Glass Mecha Reiks"},
            {"ITEM.T205", "Text: Truth Glass Mages Candlesticks"},
            {"ITEM.T206", "Text: Truth Glass Bitt"},
            {"ITEM.T207", "Text: Truth Glass Refma 2"},
            {"ITEM.T208", "Text: Truth Glass Celffy Foss"},
            {"ITEM.T209", "Text: Truth Glass Celffy Foss 2"},
            {"ITEM.T210", "Text: Truth Glass Raffy Foss"},
            {"ITEM.T211", "Text: Truth Glass Jose Harven"},
            {"ITEM.T212", "Text: Truth Glass Nola Bagil"},
            {"ITEM.T213", "Text: Truth Glass Meryl"},
            {"ITEM.T214", "Text: Truth Glass Gigi Budwell"},
            {"ITEM.T215", "Text: Truth Glass Gigi Budwell 2"},
            {"ITEM.T216", "Text: Truth Glass Teo Budwell"},
            {"ITEM.T217", "Text: Truth Glass Teo Budwell 2"},
            {"ITEM.T218", "Text: Truth Glass Teo Budwell 3"},
            {"ITEM.T219", "Text: Truth Glass Karen Shore"},
            {"ITEM.T220", "Text: Truth Glass Leon Shore"},
            {"ITEM.T221", "Text: Truth Glass Leon Shore 2"},
            {"ITEM.T222", "Text: Truth Glass Al Hunt"},
            {"ITEM.T223", "Text: Truth Glass Harris Carvitto"},
            {"ITEM.T224", "Text: Truth Glass Fai Fadlin"},
            {"ITEM.T225", "Text: Truth Glass Cliff Lore"},
            {"ITEM.T226", "Text: Truth Glass Rand Ferrer"},
            {"ITEM.T227", "Text: Truth Glass David Tabler"},
            {"ITEM.T228", "Text: Truth Glass Dalf Vice"},
            {"ITEM.T229", "Text: Truth Glass Radd Bilheim"},
            {"ITEM.T230", "Text: Truth Glass Krola Amgun"},
            {"ITEM.T231", "Text: Truth Glass Krola Amgun 2"},
            {"ITEM.T232", "Text: Truth Glass Sandler Amgun"},
            {"ITEM.T233", "Text: Truth Glass Sandler Amgun 2"},
            {"ITEM.T234", "Text: Truth Glass Mark Wozz"},
            {"ITEM.T235", "Text: Truth Glass Earnest Clyde"},
            {"ITEM.T236", "Text: Truth Glass Kehl Hunt"},
            {"ITEM.T237", "Text: Truth Glass Kehl Hunt 2"},
            {"ITEM.T238", "Text: Truth Glass Karen Shore 2"},
            {"ITEM.T239", "Text: Truth Glass The Grave Of A Saint"},
            {"ITEM.T240", "Text: Truth Glass Earnest Clyde 2"},
            {"ITEM.T241", "Text: Truth Glass Dragon Grass"},
            {"ITEM.T242", "Text: Truth Glass Miria"},
            {"ITEM.T243", "Text: Meryl Dagger"},
            {"ITEM.T244", "Text: Meryl Short Sword"},
            {"ITEM.T245", "Text: Meryl Knight Sword"},
            {"ITEM.T246", "Text: Meryl Morning Star"},
            {"ITEM.T247", "Text: Meryl Battle Hammer"},
            {"ITEM.T248", "Text: Meryl Bastard Sword"},
            {"ITEM.T249", "Text: Meryl Crescent Axe"},
            {"ITEM.T250", "Text: Meryl Flame Sword"},
            {"ITEM.T251", "Text: Meryl Shiden"},
            {"ITEM.T252", "Text: Meryl Spider"},
            {"ITEM.T253", "Text: Meryl Ice Blade"},
            {"ITEM.T254", "Text: Meryl Seath's Sword"},
            {"ITEM.T255", "Text: Meryl Moonlight Sword"},
            {"ITEM.T256", "Text: Meryl Dark Slayer"},
            {"ITEM.T257", "Text: Meryl Bow"},
            {"ITEM.T258", "Text: Meryl Arbalest"},
            {"ITEM.T259", "Text: Meryl Iron Mask"},
            {"ITEM.T260", "Text: Meryl Knight Helm"},
            {"ITEM.T261", "Text: Meryl Great Helm"},
            {"ITEM.T262", "Text: Meryl Blood Crown"},
            {"ITEM.T263", "Text: Meryl Lightning Helm"},
            {"ITEM.T264", "Text: Meryl Seath's Helm"},
            {"ITEM.T265", "Text: Meryl Breast Plate"},
            {"ITEM.T266", "Text: Meryl Knight Plate"},
            {"ITEM.T267", "Text: Meryl Ice Armor"},
            {"ITEM.T268", "Text: Meryl Dark Armor"},
            {"ITEM.T269", "Text: Meryl Seath's Armor"},
            {"ITEM.T270", "Text: Meryl Leather Shield"},
            {"ITEM.T271", "Text: Meryl Large Shield"},
            {"ITEM.T272", "Text: Meryl Moon Guard"},
            {"ITEM.T273", "Text: Meryl Crystal Guard"},
            {"ITEM.T274", "Text: Meryl Skull Shield"},
            {"ITEM.T275", "Text: Meryl Seaths Shield"},
            {"ITEM.T276", "Text: Meryl Iron Gloves"},
            {"ITEM.T277", "Text: Meryl Stone Hands"},
            {"ITEM.T278", "Text: Meryl Silver Arms"},
            {"ITEM.T279", "Text: Meryl Demon's Hands"},
            {"ITEM.T280", "Text: Meryl Ruinous Gloves"},
            {"ITEM.T281", "Text: Meryl Iron Boots"},
            {"ITEM.T282", "Text: Meryl Leg Guarders"},
            {"ITEM.T283", "Text: Meryl Silver Boots"},
            {"ITEM.T284", "Text: Meryl Death Walkers"},
            {"ITEM.T285", "Text: Meryl Ruinous Boots"},
            {"ITEM.T286", "Text: Meryl Scorpion's Bracelet"},
            {"ITEM.T287", "Text: Meryl Seath's Tear"},
            {"ITEM.T288", "Text: Meryl Seath's Bracelet"},
            {"ITEM.T289", "Text: Meryl Earth Ring"},
            {"ITEM.T290", "Text: Meryl Psycpros Collar"},
            {"ITEM.T291", "Text: Meryl Amulet Of Mist"},
            {"ITEM.T292", "Text: Meryl Lightwave Ring"},
            {"ITEM.T293", "Text: Meryl Pirate's Map"},
            {"ITEM.T294", "Text: Meryl Miner's Map"},
            {"ITEM.T295", "Text: Meryl Necron's Map"},
            {"ITEM.T296", "Text: Meryl Blood Stone"},
            {"ITEM.T297", "Text: Meryl Moon Stone"},
            {"ITEM.T298", "Text: Meryl Verdite"},
            {"ITEM.T299", "Text: Meryl Earth Herb"},
            {"ITEM.T300", "Text: Meryl Antidote"},
            {"ITEM.T301", "Text: Meryl Dragon Crystal"},
            {"ITEM.T302", "Text: Meryl Blue Potion"},
            {"ITEM.T303", "Text: Meryl Red Potion"},
            {"ITEM.T304", "Text: Meryl Green Potion"},
            {"ITEM.T305", "Text: Meryl Gold Potion"},
            {"ITEM.T306", "Text: Meryl Crystal Flask"},
            {"ITEM.T307", "Text: Meryl Figure Of Seath"},
            {"ITEM.T308", "Text: Meryl Phantom Rod"},
            {"ITEM.T309", "Text: Meryl Truth Glass"},
            {"ITEM.T310", "Text: Meryl Seath's Plume"},
            {"ITEM.T311", "Text: Meryl Demon's Pick"},
            {"ITEM.T312", "Text: Meryl Harvine's Flute"},
            {"ITEM.T313", "Text: Meryl Ground Bell"},
            {"ITEM.T314", "Text: Meryl Fire Crystal"},
            {"ITEM.T315", "Text: Meryl Water Crystal"},
            {"ITEM.T316", "Text: Meryl Earth Crystal"},
            {"ITEM.T317", "Text: Meryl Wind Crystal"},
            {"ITEM.T318", "Text: Meryl Light Crystal"},
            {"ITEM.T319", "Text: Meryl Dark Crystal"},
            {"ITEM.T320", "Text: Meryl Crystal"},
            {"ITEM.T321", "Text: Meryl Crystal Shard"},
            {"ITEM.T322", "Text: Meryl Elf's Key"},
            {"ITEM.T323", "Text: Meryl Pirates Key"},
            {"ITEM.T324", "Text: Meryl Skull Key"},
            {"ITEM.T325", "Text: Meryl Jail Key"},
            {"ITEM.T326", "Text: Meryl Rhombus Key"},
            {"ITEM.T327", "Text: Meryl Harvine's Key"},
            {"ITEM.T328", "Text: Meryl Dragon Stone"},
            {"ITEM.T329", "Text: Meryl Magician's Key"},
            {"ITEM.T330", "Text: Meryl Silver Key"},
            {"ITEM.T331", "Text: Meryl Gold Key"},
            {"ITEM.T332", "Text: Meryl Shrine Key"},
            {"ITEM.T333", "Text: Meryl Moon Gate"},
            {"ITEM.T334", "Text: Meryl Star Gate"},
            {"ITEM.T335", "Text: Meryl Sun Gate"},
            {"ITEM.T336", "Text: Meryl Moon Key"},
            {"ITEM.T337", "Text: Meryl Star Key"},
            {"ITEM.T338", "Text: Meryl Sun Key"},
            {"ITEM.T339", "Text: Meryl Arrow For The Bow"},
            {"ITEM.T340", "Text: Meryl Elf's Bolt"},
            {"ITEM.T365", "Text: Truth Glass West Seaside"},
            {"ITEM.T366", "Text: Truth Glass The Pirate's Cave"},
            {"ITEM.T367", "Text: Truth Glass Cave Of Old Hand"},
            {"ITEM.T368", "Text: Truth Glass The Mage's Lighthouse"},
            {"ITEM.T369", "Text: Truth Glass The North Village"},
            {"ITEM.T370", "Text: Truth Glass The South Village"},
            {"ITEM.T371", "Text: Truth Glass ASmall Mine"},
            {"ITEM.T372", "Text: Truth Glass The North Graveyard"},
            {"ITEM.T373", "Text: Truth Glass Base No 1"},
            {"ITEM.T374", "Text: Truth Glass Base No 2"},
            {"ITEM.T375", "Text: Truth Glass Base No 3"},
            {"ITEM.T376", "Text: Truth Glass Base No 4"},
            {"ITEM.T377", "Text: Truth Glass Base No 5"},
            {"ITEM.T378", "Text: Truth Glass Base No 6"},
            {"ITEM.T379", "Text: Truth Glass The Ruins Of King Harvine's Castle"},
            {"ITEM.T380", "Text: Truth Glass The Termite's Nest"},
            {"ITEM.T381", "Text: Truth Glass The Cemetery"},
            {"ITEM.T382", "Text: Truth Glass The Soldier's Cemetery"},
            {"ITEM.T383", "Text: Truth Glass The Window Of Homesickness"},
            {"ITEM.T384", "Text: Truth Glass The Elf Graveyard"},
            {"ITEM.T385", "Text: Truth Glass The East Village"},
            {"ITEM.T386", "Text: Truth Glass The Elf Shrine"},
            {"ITEM.T387", "Text: Truth Glass Seath's Fountain"},
            {"ITEM.T388", "Text: Truth Glass The Magic Palace Of Fire"},
            {"ITEM.T389", "Text: Truth Glass The Magic Palace Of Ice"},
            {"ITEM.T390", "Text: Truth Glass The Demon's Grave"},
            {"ITEM.T391", "Text: Truth Glass The South Graveyard"},
            {"ITEM.T392", "Text: Truth Glass The Big Mine"},
            {"ITEM.T393", "Text: Truth Glass The Poisoned Cave"},
            {"ITEM.T394", "Text: Truth Glass The Cave Of The Darkside"},
            {"ITEM.T395", "Text: Truth Glass The Elf Cave"},
            {"ITEM.T396", "Text: Truth Glass The Cave Of The Earth Soul"},
            {"ITEM.T397", "Text: Truth Glass The Lookout"},
            {"ITEM.T398", "Text: Truth Glass Necron's Coliseum"},
            {"ITEM.T399", "Text: Truth Glass The Warriors Graveyard"},
            {"ITEM.T400", "Text: Truth Glass The Research Office"},
            {"ITEM.T401", "Text: Truth Glass The Village Of The Wind"},
            {"ITEM.T402", "Text: Truth Glass The East Seaside"},

            {"MO.T0", "Slime"},
            {"MO.T1", "Poison Slime"},
            {"MO.T2", "Sigill"},
            {"MO.T3", "Baltail (Body)"},
            {"MO.T4", "Baltail (Tail)"},
            {"MO.T5", "Sting Fly (Body)"},
            {"MO.T6", "Sting Fly (Tail)"},
            {"MO.T7", "Fire Elemental"},
            {"MO.T8", "Ghost"},
            {"MO.T9", "Reik"},
            {"MO.T10", "Slime"},
            {"MO.T11", "Slime"},
            {"MO.T12", "Head Eater"},
            {"MO.T13", "Mogle"},
            {"MO.T14", "S-Knight"},
            {"MO.T15", "Necron's Soldier"},
            {"MO.T16", "Archer"},
            {"MO.T17", "Slime"},
            {"MO.T18", "Skeleton"},
            {"MO.T19", "Termite"},
            {"MO.T20", "Kald"},
            {"MO.T21", "Psythe"},
            {"MO.T22", "Termite Queen"},
            {"MO.T23", "Spike Ball (trap)"},
            {"MO.T24", "Log Stalker"},
            {"MO.T25", "Demon Lord"},
            {"MO.T26", "Kraken (Body)"},
            {"MO.T27", "Kraken (Shell)"},
            {"MO.T28", "Earth Elemental"},
            {"MO.T29", "Refma"},
            {"MO.T30", "Tarn"},
            {"MO.T31", "Copper Knight"},
            {"MO.T32", "Necron"},
            {"MO.T33", "Slime"},
            {"MO.T34", "Slime"},
            {"MO.T35", "Slime"},
            {"MO.T36", "Guyra"},
            {"MO.T37", "Salamander"},
            {"MO.T38", "Flame Spirit"},
            {"MO.T39", "Billent"},
            {"MO.T40", "Slime"},
            {"MO.T41", "Skeleton of One Eyed Giant"},
            {"MO.T42", "Picture of a King"},
            {"MO.T43", "Mecha Demon Lord"},
            {"MO.T44", "Mecha Termite"},
            {"MO.T45", "Mecha Reik"},
            {"MO.T46", "Magician's Lamp"},
            {"MO.T47", "Bitt"},
            {"MO.T48", "Refma"},
            {"MO.T49", "Cellfy Foss"},
            {"MO.T50", "Cellfy Foss"},
            {"MO.T51", "Raffy Foss"},
            {"MO.T52", "Jose Harven"},
            {"MO.T53", "Nola Bagil"},
            {"MO.T54", "Meryl"},
            {"MO.T55", "Gigi Budwell"},
            {"MO.T56", "Gigi Budwell (Watering)"},
            {"MO.T57", "Teo Budwell"},
            {"MO.T58", "Teo Budwell (With Gigi)"},
            {"MO.T59", "Teo Budwell (Mowing)"},
            {"MO.T60", "Karen Shore"},
            {"MO.T61", "Leon Shore"},
            {"MO.T62", "Leon Shore (Watering)"},
            {"MO.T63", "Al Hunt"},
            {"MO.T64", "Harris Carvitto"},
            {"MO.T65", "Fai Fadlin"},
            {"MO.T66", "Cliff Lore"},
            {"MO.T67", "Rand Ferrer"},
            {"MO.T68", "David Tabler"},
            {"MO.T69", "Dalf Vice"},
            {"MO.T70", "Radd Bilheim"},
            {"MO.T71", "Krola Amgun"},
            {"MO.T72", "Krola Amgun (Cooking)"},
            {"MO.T73", "Sandler Amgun"},
            {"MO.T74", "Sandler Amgun"},
            {"MO.T75", "Mark Wozz"},
            {"MO.T76", "Earnest Clyde"},
            {"MO.T77", "Kehl Hunt"},
            {"MO.T78", "Kehl Hunt"},
            {"MO.T79", "Karen Shore (Chair)"},
            {"MO.T80", "Jose Haven (Death)"},
            {"MO.T81", "Saint Grave"},
            {"MO.T82", "Earnest Clyde (Sitting)"},
            {"MO.T83", "Dragon Grass"},
            {"MO.T84", "Jose Haven (Death)"},
            {"MO.T85", "Miria"},
            {"MO.T86", "Dagger"},
            {"MO.T87", "Short Sword"},
            {"MO.T88", "Knight Sword"},
            {"MO.T89", "Morning Star"},
            {"MO.T90", "Battle Hammer"},
            {"MO.T91", "Bastard Sword"},
            {"MO.T92", "Crescent Axe"},
            {"MO.T93", "Default Model"},
            {"MO.T94", "Seath's Sword (And Wall)"},
            {"MO.T95", "Flame Sword"},
            {"MO.T96", "Shiden"},
            {"MO.T97", "Spider"},
            {"MO.T98", "Ice Blade"},
            {"MO.T99", "Seath's Sword"},
            {"MO.T100", "Moonlight Sword"},
            {"MO.T101", "Dark Slayer"},
            {"MO.T102", "Bow"},
            {"MO.T103", "Arbalest"},
            {"MO.T104", "Seath's Sword (Broken)"},
            {"MO.T105", "Default Model"},
            {"MO.T106", "Default Model"},
            {"MO.T107", "Iron Mask"},
            {"MO.T108", "Knight Helm"},
            {"MO.T109", "Great Helm"},
            {"MO.T110", "Blood Crown"},
            {"MO.T111", "Lightning Helm"},
            {"MO.T112", "Seath's Helm"},
            {"MO.T113", "Default Model"},

            {"RTIM.T0", "Western Shore Texture Database"},
            {"RTIM.T1", "Garrison Texture Database"},
            {"RTIM.T2", "Central Village Texture Database"},
            {"RTIM.T3", "East Village Texture Database"},
            {"RTIM.T4", "Cathedral Texture Database"},
            {"RTIM.T5", "Big Mine Texture Database"},
            {"RTIM.T6", "Necron's Coliseum Texture Database"},
            {"RTIM.T7", "Guyra's Lair Texture Database"},
            {"RTIM.T8", "Weird Debug Map Texture Database"},
            {"RTIM.T16", "Picture of a King"},
            {"RTIM.T23", "Village House 01"},
            {"RTIM.T24", "Village House 02"},
            {"RTIM.T28", "Seath's Door"},
            {"RTIM.T29", "The Picture of Warriors"},
            {"RTIM.T65", "Seath's Floor and Door"},

            {"RTMD.T0", "Western Shore Tileset"},
            {"RTMD.T1", "Garrison Tileset"},
            {"RTMD.T2", "Central Village Tileset"},
            {"RTMD.T3", "East Village Tileset"},
            {"RTMD.T4", "Cathedral Tileset"},
            {"RTMD.T5", "Big Mine Tileset"},
            {"RTMD.T6", "Necron's Coliseum Tileset"},
            {"RTMD.T7", "Guyra's Lair Tileset"},
            {"RTMD.T8", "Weird Debug Map Tileset"},

            {"VAB.T1", "Sound Effects Waveforms"},
            {"VAB.T112", "Western Shore Sequence"},
            {"VAB.T113", "Garrison Sequence"},
            {"VAB.T114", "Central Village Sequence"},
            {"VAB.T115", "East Village Sequence"},
            {"VAB.T116", "Cathedral Sequence"},
            {"VAB.T117", "Big Mine Sequence"},
            {"VAB.T118", "Necrons Coliseum Sequence"},
            {"VAB.T119", "Guyras Lair Sequence"},
            {"VAB.T121", "Central Village 2 Sequence"},
        };
};

#endif // PRETTYNAMER_H
