#include "prettynames.h"
namespace PrettyNames
{
const QHash<const QString, QString> prettyKF2{
    {QStringLiteral("FDAT.T0"), QStringLiteral("Western Shore Tilemap")},
    {QStringLiteral("FDAT.T1"), QStringLiteral("Western Shore Map DB")},
    {QStringLiteral("FDAT.T2"), QStringLiteral("Western Shore Script")},
    {QStringLiteral("FDAT.T3"), QStringLiteral("Garrison Tilemap")},
    {QStringLiteral("FDAT.T4"), QStringLiteral("Garrison Map DB")},
    {QStringLiteral("FDAT.T5"), QStringLiteral("Garrison Script")},
    {QStringLiteral("FDAT.T6"), QStringLiteral("Central Village Tilemap")},
    {QStringLiteral("FDAT.T7"), QStringLiteral("Central Village Map DB")},
    {QStringLiteral("FDAT.T8"), QStringLiteral("Central Village Script")},
    {QStringLiteral("FDAT.T9"), QStringLiteral("East Village Tilemap")},
    {QStringLiteral("FDAT.T10"), QStringLiteral("East Village Map DB")},
    {QStringLiteral("FDAT.T11"), QStringLiteral("East Village Script")},
    {QStringLiteral("FDAT.T12"), QStringLiteral("Cathedral Tilemap")},
    {QStringLiteral("FDAT.T13"), QStringLiteral("Cathedral Map DB")},
    {QStringLiteral("FDAT.T14"), QStringLiteral("Cathedral Script")},
    {QStringLiteral("FDAT.T15"), QStringLiteral("Big Mine Tilemap")},
    {QStringLiteral("FDAT.T16"), QStringLiteral("Big Mine Map DB")},
    {QStringLiteral("FDAT.T17"), QStringLiteral("Big Mine Script")},
    {QStringLiteral("FDAT.T18"), QStringLiteral("Necron's Coliseum Tilemap")},
    {QStringLiteral("FDAT.T19"), QStringLiteral("Necron's Coliseum Map DB")},
    {QStringLiteral("FDAT.T20"), QStringLiteral("Necron's Coliseum Script")},
    {QStringLiteral("FDAT.T21"), QStringLiteral("Guyra's Lair Tilemap")},
    {QStringLiteral("FDAT.T22"), QStringLiteral("Guyra's Lair Map DB")},
    {QStringLiteral("FDAT.T23"), QStringLiteral("Guyra's Lair Script")},
    {QStringLiteral("FDAT.T24"), QStringLiteral("Weird Debug Map Tilemap")},
    {QStringLiteral("FDAT.T25"), QStringLiteral("Weird Debug Map Map DB")},
    {QStringLiteral("FDAT.T26"), QStringLiteral("Weird Debug Map Script")},
    {QStringLiteral("FDAT.T27"), QStringLiteral("Texture Database")},
    {QStringLiteral("FDAT.T28"), QStringLiteral("Game Database")},
    {QStringLiteral("FDAT.T29"), QStringLiteral("Dagger Viewmodel")},
    {QStringLiteral("FDAT.T30"), QStringLiteral("Short Sword Viewmodel")},
    {QStringLiteral("FDAT.T31"), QStringLiteral("Knight Sword Viewmodel")},
    {QStringLiteral("FDAT.T32"), QStringLiteral("Morning Star Viewmodel")},
    {QStringLiteral("FDAT.T33"), QStringLiteral("Battle Hammer Viewmodel")},
    {QStringLiteral("FDAT.T34"), QStringLiteral("Bastard Sword Viewmodel")},
    {QStringLiteral("FDAT.T35"), QStringLiteral("Crescent Axe Viewmodel")},
    {QStringLiteral("FDAT.T36"), QStringLiteral("Flame Sword Viewmodel")},
    {QStringLiteral("FDAT.T37"), QStringLiteral("Shiden Viewmodel")},
    {QStringLiteral("FDAT.T38"), QStringLiteral("Spider Viewmodel")},
    {QStringLiteral("FDAT.T39"), QStringLiteral("Ice Blade Viewmodel")},
    {QStringLiteral("FDAT.T40"), QStringLiteral("Seath's Sword Viewmodel")},
    {QStringLiteral("FDAT.T41"), QStringLiteral("Moonlight Sword Viewmodel")},
    {QStringLiteral("FDAT.T42"), QStringLiteral("Dark Slayer Viewmodel")},
    {QStringLiteral("FDAT.T43"), QStringLiteral("Bow Viewmodel")},
    {QStringLiteral("FDAT.T44"), QStringLiteral("Arbalest Viewmodel")},

    {QStringLiteral("ITEM.T0"), QStringLiteral("Dagger Model")},
    {QStringLiteral("ITEM.T1"), QStringLiteral("Short Sword Model")},
    {QStringLiteral("ITEM.T2"), QStringLiteral("Knight Sword Model")},
    {QStringLiteral("ITEM.T3"), QStringLiteral("Morning Star Model")},
    {QStringLiteral("ITEM.T4"), QStringLiteral("Battle Hammer Model")},
    {QStringLiteral("ITEM.T5"), QStringLiteral("Bastard Sword Model")},
    {QStringLiteral("ITEM.T6"), QStringLiteral("Crescent Axe Model")},
    {QStringLiteral("ITEM.T7"), QStringLiteral("Flame Sword Model")},
    {QStringLiteral("ITEM.T8"), QStringLiteral("Shiden Model")},
    {QStringLiteral("ITEM.T9"), QStringLiteral("Spider Model")},
    {QStringLiteral("ITEM.T10"), QStringLiteral("Ice Blade Model")},
    {QStringLiteral("ITEM.T11"), QStringLiteral("Seath's Sword Model")},
    {QStringLiteral("ITEM.T12"), QStringLiteral("Moonlight Sword Model")},
    {QStringLiteral("ITEM.T13"), QStringLiteral("Dark Slayer Model")},
    {QStringLiteral("ITEM.T14"), QStringLiteral("Bow Model")},
    {QStringLiteral("ITEM.T15"), QStringLiteral("Arbalest Model")},
    {QStringLiteral("ITEM.T16"), QStringLiteral("Iron Mask Model")},
    {QStringLiteral("ITEM.T17"), QStringLiteral("Knight Helm Model")},
    {QStringLiteral("ITEM.T18"), QStringLiteral("Great Helm Model")},
    {QStringLiteral("ITEM.T19"), QStringLiteral("Blood Crown Model")},
    {QStringLiteral("ITEM.T20"), QStringLiteral("Lightning Helm Model")},
    {QStringLiteral("ITEM.T21"), QStringLiteral("Seath's Helm Model")},
    {QStringLiteral("ITEM.T22"), QStringLiteral("Breast Plate Model")},
    {QStringLiteral("ITEM.T23"), QStringLiteral("Knight Plate Model")},
    {QStringLiteral("ITEM.T24"), QStringLiteral("Ice Armor Model")},
    {QStringLiteral("ITEM.T25"), QStringLiteral("Dark Armor Model")},
    {QStringLiteral("ITEM.T26"), QStringLiteral("Seath's Armor Model")},
    {QStringLiteral("ITEM.T27"), QStringLiteral("Leather Shield Model")},
    {QStringLiteral("ITEM.T28"), QStringLiteral("Large Shield Model")},
    {QStringLiteral("ITEM.T29"), QStringLiteral("Moon Guard Model")},
    {QStringLiteral("ITEM.T30"), QStringLiteral("Crystal Guard Model")},
    {QStringLiteral("ITEM.T31"), QStringLiteral("Skull Shield Model")},
    {QStringLiteral("ITEM.T32"), QStringLiteral("Seath's Shield Model")},
    {QStringLiteral("ITEM.T33"), QStringLiteral("Iron Gloves Model")},
    {QStringLiteral("ITEM.T34"), QStringLiteral("Stone Hands Model")},
    {QStringLiteral("ITEM.T35"), QStringLiteral("Silver Arms Model")},
    {QStringLiteral("ITEM.T36"), QStringLiteral("Demon's Hands Model")},
    {QStringLiteral("ITEM.T37"), QStringLiteral("Ruinous Gloves Model")},
    {QStringLiteral("ITEM.T38"), QStringLiteral("Iron Boots Model")},
    {QStringLiteral("ITEM.T39"), QStringLiteral("Leg Guarders Model")},
    {QStringLiteral("ITEM.T40"), QStringLiteral("Silver Boots Model")},
    {QStringLiteral("ITEM.T41"), QStringLiteral("Death Walkers Model")},
    {QStringLiteral("ITEM.T42"), QStringLiteral("Ruinous Boots Model")},
    {QStringLiteral("ITEM.T43"), QStringLiteral("Scorpion's Bracelet Model")},
    {QStringLiteral("ITEM.T44"), QStringLiteral("Seath's Tear Model")},
    {QStringLiteral("ITEM.T45"), QStringLiteral("Seath's Bracelet Model")},
    {QStringLiteral("ITEM.T46"), QStringLiteral("Earth Ring Model")},
    {QStringLiteral("ITEM.T47"), QStringLiteral("Psycpros Collar Model")},
    {QStringLiteral("ITEM.T48"), QStringLiteral("Amulet Of Mist Model")},
    {QStringLiteral("ITEM.T49"), QStringLiteral("Lightwave Ring Model")},
    {QStringLiteral("ITEM.T50"), QStringLiteral("Pirate's Map Model")},
    {QStringLiteral("ITEM.T51"), QStringLiteral("Miner's Map Model")},
    {QStringLiteral("ITEM.T52"), QStringLiteral("Necron's Map Model")},
    {QStringLiteral("ITEM.T53"), QStringLiteral("Gold Coin Model")},
    {QStringLiteral("ITEM.T54"), QStringLiteral("Blood Stone Model")},
    {QStringLiteral("ITEM.T55"), QStringLiteral("Moon Stone Model")},
    {QStringLiteral("ITEM.T56"), QStringLiteral("Verdite Model")},
    {QStringLiteral("ITEM.T57"), QStringLiteral("Earth Herb Model")},
    {QStringLiteral("ITEM.T58"), QStringLiteral("Antidote Model")},
    {QStringLiteral("ITEM.T59"), QStringLiteral("Dragon Crystal Model")},
    {QStringLiteral("ITEM.T60"), QStringLiteral("Blue Potion Model")},
    {QStringLiteral("ITEM.T61"), QStringLiteral("Red Potion Model")},
    {QStringLiteral("ITEM.T62"), QStringLiteral("Green Potion Model")},
    {QStringLiteral("ITEM.T63"), QStringLiteral("Gold Potion Model")},
    {QStringLiteral("ITEM.T64"), QStringLiteral("\"A\" Potion Model")},
    {QStringLiteral("ITEM.T65"), QStringLiteral("Crystal Flask Model")},
    {QStringLiteral("ITEM.T66"), QStringLiteral("Figure Of Seath Model")},
    {QStringLiteral("ITEM.T67"), QStringLiteral("Phantom Rod Model")},
    {QStringLiteral("ITEM.T68"), QStringLiteral("Truth Glass Model")},
    {QStringLiteral("ITEM.T69"), QStringLiteral("Seath's Plume Model")},
    {QStringLiteral("ITEM.T70"), QStringLiteral("Demon's Pick Model")},
    {QStringLiteral("ITEM.T71"), QStringLiteral("Harvine's Flute Model")},
    {QStringLiteral("ITEM.T72"), QStringLiteral("Ground Bell Model")},
    {QStringLiteral("ITEM.T73"), QStringLiteral("Fire Crystal Model")},
    {QStringLiteral("ITEM.T74"), QStringLiteral("Water Crystal Model")},
    {QStringLiteral("ITEM.T75"), QStringLiteral("Earth Crystal Model")},
    {QStringLiteral("ITEM.T76"), QStringLiteral("Wind Crystal Model")},
    {QStringLiteral("ITEM.T77"), QStringLiteral("Light Crystal Model")},
    {QStringLiteral("ITEM.T78"), QStringLiteral("Dark Crystal Model")},
    {QStringLiteral("ITEM.T79"), QStringLiteral("Crystal Model")},
    {QStringLiteral("ITEM.T80"), QStringLiteral("Crystal Shard Model")},
    {QStringLiteral("ITEM.T81"), QStringLiteral("\"A\" Ring Model")},
    {QStringLiteral("ITEM.T82"), QStringLiteral("Elf's Key Model")},
    {QStringLiteral("ITEM.T83"), QStringLiteral("Pirate's Key Model")},
    {QStringLiteral("ITEM.T84"), QStringLiteral("Skull Key Model")},
    {QStringLiteral("ITEM.T85"), QStringLiteral("Jail Key Model")},
    {QStringLiteral("ITEM.T86"), QStringLiteral("Rhombus Key Model")},
    {QStringLiteral("ITEM.T87"), QStringLiteral("Harvine's Key Model")},
    {QStringLiteral("ITEM.T88"), QStringLiteral("Dragon Stone Model")},
    {QStringLiteral("ITEM.T89"), QStringLiteral("Magician's Key Model")},
    {QStringLiteral("ITEM.T90"), QStringLiteral("Silver Key Model")},
    {QStringLiteral("ITEM.T91"), QStringLiteral("Gold Key Model")},
    {QStringLiteral("ITEM.T92"), QStringLiteral("Shrine Key Model")},
    {QStringLiteral("ITEM.T93"), QStringLiteral("\"A\" Herb Model")},
    {QStringLiteral("ITEM.T94"), QStringLiteral("Moon Gate Model")},
    {QStringLiteral("ITEM.T95"), QStringLiteral("Star Gate Model")},
    {QStringLiteral("ITEM.T96"), QStringLiteral("Sun Gate Model")},
    {QStringLiteral("ITEM.T97"), QStringLiteral("Moon Key Model")},
    {QStringLiteral("ITEM.T98"), QStringLiteral("Star Key Model")},
    {QStringLiteral("ITEM.T99"), QStringLiteral("Sun Key Model")},
    {QStringLiteral("ITEM.T100"), QStringLiteral("Arrow For The Bow Model")},
    {QStringLiteral("ITEM.T101"), QStringLiteral("Elf's Bolt Model")},
    {QStringLiteral("ITEM.T102"), QStringLiteral("\"A\" Herb 2 Model")},
    {QStringLiteral("ITEM.T103"), QStringLiteral("Text: Al Hunt")},
    {QStringLiteral("ITEM.T104"), QStringLiteral("Text: Nola Bagil")},
    {QStringLiteral("ITEM.T105"), QStringLiteral("Text: Mark Wozz")},
    {QStringLiteral("ITEM.T106"), QStringLiteral("Text: Rand Ferrer")},
    {QStringLiteral("ITEM.T107"), QStringLiteral("Text: Radd Bilheim")},
    {QStringLiteral("ITEM.T108"), QStringLiteral("Text: Kehl Hunt")},
    {QStringLiteral("ITEM.T109"), QStringLiteral("Text: Krola Sandler Amgun")},
    {QStringLiteral("ITEM.T110"), QStringLiteral("Text: Cliff Lore")},
    {QStringLiteral("ITEM.T111"), QStringLiteral("Text: David Tabler")},
    {QStringLiteral("ITEM.T112"), QStringLiteral("Text: Dalf Vice")},
    {QStringLiteral("ITEM.T113"), QStringLiteral("Text: Harris Carvitto")},
    {QStringLiteral("ITEM.T114"), QStringLiteral("Text: Teo Gigi Budwell")},
    {QStringLiteral("ITEM.T115"), QStringLiteral("Text: Karen Leon Shore")},
    {QStringLiteral("ITEM.T116"), QStringLiteral("Text: Base No1")},
    {QStringLiteral("ITEM.T117"), QStringLiteral("Text: Base No2")},
    {QStringLiteral("ITEM.T118"), QStringLiteral("Text: Base No3")},
    {QStringLiteral("ITEM.T119"), QStringLiteral("Text: Base No4")},
    {QStringLiteral("ITEM.T120"), QStringLiteral("Text: Base No5")},
    {QStringLiteral("ITEM.T121"), QStringLiteral("Text: Base No6")},
    {QStringLiteral("ITEM.T122"), QStringLiteral("Text: The Magic Cave Of Ice")},
    {QStringLiteral("ITEM.T123"), QStringLiteral("Text: Base No7")},
    {QStringLiteral("ITEM.T124"), QStringLiteral("Text: The Entrance To The North Village")},
    {QStringLiteral("ITEM.T125"), QStringLiteral("Text: The Entrance To The South Village")},
    {QStringLiteral("ITEM.T126"), QStringLiteral("Text: The Space For Completion No Trespassing")},
    {QStringLiteral("ITEM.T127"), QStringLiteral("Text: The Entrance To The Central Village")},
    {QStringLiteral("ITEM.T128"), QStringLiteral("Text: The Entrance To The Big Mine")},
    {QStringLiteral("ITEM.T129"), QStringLiteral("Text: The Underworld Prison No1")},
    {QStringLiteral("ITEM.T130"), QStringLiteral("Text: The Underworld Prison No2")},
    {QStringLiteral("ITEM.T131"),
     QStringLiteral("Text: The Cemetery For The Military Guards Of King Harvine III")},
    {QStringLiteral("ITEM.T132"), QStringLiteral("Text: Royal Treasure House")},
    {QStringLiteral("ITEM.T133"), QStringLiteral("Text: The Magic Cave Of Fire")},
    {QStringLiteral("ITEM.T134"),
     QStringLiteral("Text: Warriors Who Were Killed By Guyras Legion Are Buried Here")},
    {"ITEM.T135",
     "Text: The Souls Of The Guards Who Were Killed Are Waiting To Watch The Next Fight"},
    {"ITEM.T136",
     "Text: The King Of Winds King Harvine IIIHad Started To Construct His Castle Here"},
    {QStringLiteral("ITEM.T137"),
     QStringLiteral(
         "Text: The Castle Of The Great Ruler Of The Northern Continent King Harvine III")},
    {QStringLiteral("ITEM.T138"), QStringLiteral("Text: Danger Ahead")},
    {QStringLiteral("ITEM.T139"),
     QStringLiteral(
         "Text: In The Name Of The Great Mage No One Can Enter This Cave Of Earth Soul")},
    {"ITEM.T140",
     "Text: Galth Free The Demon Of The Darkside Died With The High Elves He Is A Phantom Of "
     "The "
     "World"},
    {QStringLiteral("ITEM.T141"),
     QStringLiteral("Text: A Message From The East Land Rest In Peace Here")},
    {"ITEM.T142",
     "Text: Most Soldiers Have Already Died There Is No Way To Leave The Island We Realize "
     "That "
     "There Is No Way Back Home"},
    {"ITEM.T143",
     "Text: In The Name Of Tsedeck The Mage Of Fire Who Defeated King Harvine III And Ruled "
     "The "
     "Northern Continent"},
    {QStringLiteral("ITEM.T144"), QStringLiteral("Text: Gigis House Sandler")},
    {QStringLiteral("ITEM.T145"),
     QStringLiteral("Text: They Can Be Attacked By Bows Take Good Aim")},
    {QStringLiteral("ITEM.T146"), QStringLiteral("Text: Do Not Enter Old Hand")},
    {QStringLiteral("ITEM.T147"), QStringLiteral("Text: Medical Herbs For Sale Al Hunt")},
    {QStringLiteral("ITEM.T148"), QStringLiteral("Text: The South Graveyard To The Small Mine")},
    {QStringLiteral("ITEM.T149"), QStringLiteral("Text: Termites Nest Ahead Watch Your Step")},
    {"ITEM.T150",
     "Text: My Beloved Son You Have Fought For Me And Have Lost Your Life For Me May You Rest "
     "In "
     "Peace"},
    {QStringLiteral("ITEM.T151"), QStringLiteral("Text: Do Not Get Closer Krakens Nest")},
    {QStringLiteral("ITEM.T152"), QStringLiteral("Text: Dangerous No Exit")},
    {QStringLiteral("ITEM.T153"), QStringLiteral("Text: The Elf Cave")},
    {"ITEM.T154",
     "Text: By And By A Man Who Comes Here Beats The Black Dragon With The Blessing Of Seath"},
    {QStringLiteral("ITEM.T155"), QStringLiteral("Text: The Cave Of The Darkside This Is Hell")},
    {QStringLiteral("ITEM.T156"),
     QStringLiteral("Text: Offer Everything To Guyra Who Rules The Light And The Dark")},
    {QStringLiteral("ITEM.T157"), QStringLiteral("Text: They Are Creating Devils Be Careful")},
    {QStringLiteral("ITEM.T158"),
     QStringLiteral("Text: When The Warriors Stand Up The Great Door Will Be Opened Again")},
    {QStringLiteral("ITEM.T159"), QStringLiteral("Text: The Entrance To The Small Mine")},
    {QStringLiteral("ITEM.T160"), QStringLiteral("Text: The Poisoned Cave Dangerous")},
    {QStringLiteral("ITEM.T161"), QStringLiteral("Text: The Great Demon's Grave")},
    {QStringLiteral("ITEM.T162"), QStringLiteral("Text: Earnests Body")},
    {QStringLiteral("ITEM.T163"), QStringLiteral("Text: The Picture Of Warriors")},
    {QStringLiteral("ITEM.T164"), QStringLiteral("Text: Truth Glass Green Slime")},
    {QStringLiteral("ITEM.T165"), QStringLiteral("Text: Truth Glass Poison Slime")},
    {QStringLiteral("ITEM.T166"), QStringLiteral("Text: Truth Glass Sigill")},
    {QStringLiteral("ITEM.T167"), QStringLiteral("Text: Truth Glass Sigill 2")},
    {QStringLiteral("ITEM.T168"), QStringLiteral("Text: Truth Glass Baltail")},
    {QStringLiteral("ITEM.T169"), QStringLiteral("Text: Truth Glass Baltail 2")},
    {QStringLiteral("ITEM.T170"), QStringLiteral("Text: Truth Glass Poison Baltail")},
    {QStringLiteral("ITEM.T171"), QStringLiteral("Text: Truth Glass Poison Baltail 2")},
    {QStringLiteral("ITEM.T172"), QStringLiteral("Text: Truth Glass Fire Elemental")},
    {QStringLiteral("ITEM.T173"), QStringLiteral("Text: Truth Glass Fire Elemental 2")},
    {QStringLiteral("ITEM.T174"), QStringLiteral("Text: Truth Glass Ghosts")},
    {QStringLiteral("ITEM.T175"), QStringLiteral("Text: Truth Glass Reiks")},
    {QStringLiteral("ITEM.T176"), QStringLiteral("Text: Truth Glass Head Eater")},
    {QStringLiteral("ITEM.T177"), QStringLiteral("Text: Truth Glass Mogle")},
    {QStringLiteral("ITEM.T178"), QStringLiteral("Text: Truth Glass S-Knight")},
    {QStringLiteral("ITEM.T179"), QStringLiteral("Text: Truth Glass Necron's Soldiers")},
    {QStringLiteral("ITEM.T180"), QStringLiteral("Text: Truth Glass Archers")},
    {QStringLiteral("ITEM.T181"), QStringLiteral("Text: Truth Glass Skeleton")},
    {QStringLiteral("ITEM.T182"), QStringLiteral("Text: Truth Glass Termite")},
    {QStringLiteral("ITEM.T183"), QStringLiteral("Text: Truth Glass Kald")},
    {QStringLiteral("ITEM.T184"), QStringLiteral("Text: Truth Glass Psythe")},
    {QStringLiteral("ITEM.T185"), QStringLiteral("Text: Truth Glass Queen Termite")},
    {QStringLiteral("ITEM.T186"), QStringLiteral("Text: Truth Glass Freeze Ball")},
    {QStringLiteral("ITEM.T187"), QStringLiteral("Text: Truth Glass Log Stalker")},
    {QStringLiteral("ITEM.T188"), QStringLiteral("Text: Truth Glass Demon Lord")},
    {QStringLiteral("ITEM.T189"), QStringLiteral("Text: Truth Glass Kraken")},
    {QStringLiteral("ITEM.T190"), QStringLiteral("Text: Truth Glass Kraken 2")},
    {QStringLiteral("ITEM.T191"), QStringLiteral("Text: Truth Glass Earth Elemental")},
    {QStringLiteral("ITEM.T192"), QStringLiteral("Text: Truth Glass Refma")},
    {QStringLiteral("ITEM.T193"), QStringLiteral("Text: Truth Glass Tarn")},
    {QStringLiteral("ITEM.T194"), QStringLiteral("Text: Truth Glass Copper Knight")},
    {QStringLiteral("ITEM.T195"), QStringLiteral("Text: Truth Glass Dias Bagil")},
    {QStringLiteral("ITEM.T196"), QStringLiteral("Text: Truth Glass Guyra")},
    {QStringLiteral("ITEM.T197"), QStringLiteral("Text: Truth Glass Salamander")},
    {QStringLiteral("ITEM.T198"), QStringLiteral("Text: Truth Glass Flame Spirit")},
    {QStringLiteral("ITEM.T199"), QStringLiteral("Text: Truth Glass Billent")},
    {QStringLiteral("ITEM.T200"), QStringLiteral("Text: Truth Glass Skeleton Of One Eyed Giant")},
    {QStringLiteral("ITEM.T201"), QStringLiteral("Text: Truth Glass The Picture Of A King")},
    {QStringLiteral("ITEM.T201"), QStringLiteral("Text: Truth Glass The Picture Of A King")},
    {QStringLiteral("ITEM.T202"), QStringLiteral("Text: Truth Glass Mecha Demon Lord")},
    {QStringLiteral("ITEM.T203"), QStringLiteral("Text: Truth Glass Mecha Termite")},
    {QStringLiteral("ITEM.T204"), QStringLiteral("Text: Truth Glass Mecha Reiks")},
    {QStringLiteral("ITEM.T205"), QStringLiteral("Text: Truth Glass Mages Candlesticks")},
    {QStringLiteral("ITEM.T206"), QStringLiteral("Text: Truth Glass Bitt")},
    {QStringLiteral("ITEM.T207"), QStringLiteral("Text: Truth Glass Refma 2")},
    {QStringLiteral("ITEM.T208"), QStringLiteral("Text: Truth Glass Celffy Foss")},
    {QStringLiteral("ITEM.T209"), QStringLiteral("Text: Truth Glass Celffy Foss 2")},
    {QStringLiteral("ITEM.T210"), QStringLiteral("Text: Truth Glass Raffy Foss")},
    {QStringLiteral("ITEM.T211"), QStringLiteral("Text: Truth Glass Jose Harven")},
    {QStringLiteral("ITEM.T212"), QStringLiteral("Text: Truth Glass Nola Bagil")},
    {QStringLiteral("ITEM.T213"), QStringLiteral("Text: Truth Glass Meryl")},
    {QStringLiteral("ITEM.T214"), QStringLiteral("Text: Truth Glass Gigi Budwell")},
    {QStringLiteral("ITEM.T215"), QStringLiteral("Text: Truth Glass Gigi Budwell 2")},
    {QStringLiteral("ITEM.T216"), QStringLiteral("Text: Truth Glass Teo Budwell")},
    {QStringLiteral("ITEM.T217"), QStringLiteral("Text: Truth Glass Teo Budwell 2")},
    {QStringLiteral("ITEM.T218"), QStringLiteral("Text: Truth Glass Teo Budwell 3")},
    {QStringLiteral("ITEM.T219"), QStringLiteral("Text: Truth Glass Karen Shore")},
    {QStringLiteral("ITEM.T220"), QStringLiteral("Text: Truth Glass Leon Shore")},
    {QStringLiteral("ITEM.T221"), QStringLiteral("Text: Truth Glass Leon Shore 2")},
    {QStringLiteral("ITEM.T222"), QStringLiteral("Text: Truth Glass Al Hunt")},
    {QStringLiteral("ITEM.T223"), QStringLiteral("Text: Truth Glass Harris Carvitto")},
    {QStringLiteral("ITEM.T224"), QStringLiteral("Text: Truth Glass Fai Fadlin")},
    {QStringLiteral("ITEM.T225"), QStringLiteral("Text: Truth Glass Cliff Lore")},
    {QStringLiteral("ITEM.T226"), QStringLiteral("Text: Truth Glass Rand Ferrer")},
    {QStringLiteral("ITEM.T227"), QStringLiteral("Text: Truth Glass David Tabler")},
    {QStringLiteral("ITEM.T228"), QStringLiteral("Text: Truth Glass Dalf Vice")},
    {QStringLiteral("ITEM.T229"), QStringLiteral("Text: Truth Glass Radd Bilheim")},
    {QStringLiteral("ITEM.T230"), QStringLiteral("Text: Truth Glass Krola Amgun")},
    {QStringLiteral("ITEM.T231"), QStringLiteral("Text: Truth Glass Krola Amgun 2")},
    {QStringLiteral("ITEM.T232"), QStringLiteral("Text: Truth Glass Sandler Amgun")},
    {QStringLiteral("ITEM.T233"), QStringLiteral("Text: Truth Glass Sandler Amgun 2")},
    {QStringLiteral("ITEM.T234"), QStringLiteral("Text: Truth Glass Mark Wozz")},
    {QStringLiteral("ITEM.T235"), QStringLiteral("Text: Truth Glass Earnest Clyde")},
    {QStringLiteral("ITEM.T236"), QStringLiteral("Text: Truth Glass Kehl Hunt")},
    {QStringLiteral("ITEM.T237"), QStringLiteral("Text: Truth Glass Kehl Hunt 2")},
    {QStringLiteral("ITEM.T238"), QStringLiteral("Text: Truth Glass Karen Shore 2")},
    {QStringLiteral("ITEM.T239"), QStringLiteral("Text: Truth Glass The Grave Of A Saint")},
    {QStringLiteral("ITEM.T240"), QStringLiteral("Text: Truth Glass Earnest Clyde 2")},
    {QStringLiteral("ITEM.T241"), QStringLiteral("Text: Truth Glass Dragon Grass")},
    {QStringLiteral("ITEM.T242"), QStringLiteral("Text: Truth Glass Miria")},
    {QStringLiteral("ITEM.T243"), QStringLiteral("Text: Meryl Dagger")},
    {QStringLiteral("ITEM.T244"), QStringLiteral("Text: Meryl Short Sword")},
    {QStringLiteral("ITEM.T245"), QStringLiteral("Text: Meryl Knight Sword")},
    {QStringLiteral("ITEM.T246"), QStringLiteral("Text: Meryl Morning Star")},
    {QStringLiteral("ITEM.T247"), QStringLiteral("Text: Meryl Battle Hammer")},
    {QStringLiteral("ITEM.T248"), QStringLiteral("Text: Meryl Bastard Sword")},
    {QStringLiteral("ITEM.T249"), QStringLiteral("Text: Meryl Crescent Axe")},
    {QStringLiteral("ITEM.T250"), QStringLiteral("Text: Meryl Flame Sword")},
    {QStringLiteral("ITEM.T251"), QStringLiteral("Text: Meryl Shiden")},
    {QStringLiteral("ITEM.T252"), QStringLiteral("Text: Meryl Spider")},
    {QStringLiteral("ITEM.T253"), QStringLiteral("Text: Meryl Ice Blade")},
    {QStringLiteral("ITEM.T254"), QStringLiteral("Text: Meryl Seath's Sword")},
    {QStringLiteral("ITEM.T255"), QStringLiteral("Text: Meryl Moonlight Sword")},
    {QStringLiteral("ITEM.T256"), QStringLiteral("Text: Meryl Dark Slayer")},
    {QStringLiteral("ITEM.T257"), QStringLiteral("Text: Meryl Bow")},
    {QStringLiteral("ITEM.T258"), QStringLiteral("Text: Meryl Arbalest")},
    {QStringLiteral("ITEM.T259"), QStringLiteral("Text: Meryl Iron Mask")},
    {QStringLiteral("ITEM.T260"), QStringLiteral("Text: Meryl Knight Helm")},
    {QStringLiteral("ITEM.T261"), QStringLiteral("Text: Meryl Great Helm")},
    {QStringLiteral("ITEM.T262"), QStringLiteral("Text: Meryl Blood Crown")},
    {QStringLiteral("ITEM.T263"), QStringLiteral("Text: Meryl Lightning Helm")},
    {QStringLiteral("ITEM.T264"), QStringLiteral("Text: Meryl Seath's Helm")},
    {QStringLiteral("ITEM.T265"), QStringLiteral("Text: Meryl Breast Plate")},
    {QStringLiteral("ITEM.T266"), QStringLiteral("Text: Meryl Knight Plate")},
    {QStringLiteral("ITEM.T267"), QStringLiteral("Text: Meryl Ice Armor")},
    {QStringLiteral("ITEM.T268"), QStringLiteral("Text: Meryl Dark Armor")},
    {QStringLiteral("ITEM.T269"), QStringLiteral("Text: Meryl Seath's Armor")},
    {QStringLiteral("ITEM.T270"), QStringLiteral("Text: Meryl Leather Shield")},
    {QStringLiteral("ITEM.T271"), QStringLiteral("Text: Meryl Large Shield")},
    {QStringLiteral("ITEM.T272"), QStringLiteral("Text: Meryl Moon Guard")},
    {QStringLiteral("ITEM.T273"), QStringLiteral("Text: Meryl Crystal Guard")},
    {QStringLiteral("ITEM.T274"), QStringLiteral("Text: Meryl Skull Shield")},
    {QStringLiteral("ITEM.T275"), QStringLiteral("Text: Meryl Seaths Shield")},
    {QStringLiteral("ITEM.T276"), QStringLiteral("Text: Meryl Iron Gloves")},
    {QStringLiteral("ITEM.T277"), QStringLiteral("Text: Meryl Stone Hands")},
    {QStringLiteral("ITEM.T278"), QStringLiteral("Text: Meryl Silver Arms")},
    {QStringLiteral("ITEM.T279"), QStringLiteral("Text: Meryl Demon's Hands")},
    {QStringLiteral("ITEM.T280"), QStringLiteral("Text: Meryl Ruinous Gloves")},
    {QStringLiteral("ITEM.T281"), QStringLiteral("Text: Meryl Iron Boots")},
    {QStringLiteral("ITEM.T282"), QStringLiteral("Text: Meryl Leg Guarders")},
    {QStringLiteral("ITEM.T283"), QStringLiteral("Text: Meryl Silver Boots")},
    {QStringLiteral("ITEM.T284"), QStringLiteral("Text: Meryl Death Walkers")},
    {QStringLiteral("ITEM.T285"), QStringLiteral("Text: Meryl Ruinous Boots")},
    {QStringLiteral("ITEM.T286"), QStringLiteral("Text: Meryl Scorpion's Bracelet")},
    {QStringLiteral("ITEM.T287"), QStringLiteral("Text: Meryl Seath's Tear")},
    {QStringLiteral("ITEM.T288"), QStringLiteral("Text: Meryl Seath's Bracelet")},
    {QStringLiteral("ITEM.T289"), QStringLiteral("Text: Meryl Earth Ring")},
    {QStringLiteral("ITEM.T290"), QStringLiteral("Text: Meryl Psycpros Collar")},
    {QStringLiteral("ITEM.T291"), QStringLiteral("Text: Meryl Amulet Of Mist")},
    {QStringLiteral("ITEM.T292"), QStringLiteral("Text: Meryl Lightwave Ring")},
    {QStringLiteral("ITEM.T293"), QStringLiteral("Text: Meryl Pirate's Map")},
    {QStringLiteral("ITEM.T294"), QStringLiteral("Text: Meryl Miner's Map")},
    {QStringLiteral("ITEM.T295"), QStringLiteral("Text: Meryl Necron's Map")},
    {QStringLiteral("ITEM.T296"), QStringLiteral("Text: Meryl Blood Stone")},
    {QStringLiteral("ITEM.T297"), QStringLiteral("Text: Meryl Moon Stone")},
    {QStringLiteral("ITEM.T298"), QStringLiteral("Text: Meryl Verdite")},
    {QStringLiteral("ITEM.T299"), QStringLiteral("Text: Meryl Earth Herb")},
    {QStringLiteral("ITEM.T300"), QStringLiteral("Text: Meryl Antidote")},
    {QStringLiteral("ITEM.T301"), QStringLiteral("Text: Meryl Dragon Crystal")},
    {QStringLiteral("ITEM.T302"), QStringLiteral("Text: Meryl Blue Potion")},
    {QStringLiteral("ITEM.T303"), QStringLiteral("Text: Meryl Red Potion")},
    {QStringLiteral("ITEM.T304"), QStringLiteral("Text: Meryl Green Potion")},
    {QStringLiteral("ITEM.T305"), QStringLiteral("Text: Meryl Gold Potion")},
    {QStringLiteral("ITEM.T306"), QStringLiteral("Text: Meryl Crystal Flask")},
    {QStringLiteral("ITEM.T307"), QStringLiteral("Text: Meryl Figure Of Seath")},
    {QStringLiteral("ITEM.T308"), QStringLiteral("Text: Meryl Phantom Rod")},
    {QStringLiteral("ITEM.T309"), QStringLiteral("Text: Meryl Truth Glass")},
    {QStringLiteral("ITEM.T310"), QStringLiteral("Text: Meryl Seath's Plume")},
    {QStringLiteral("ITEM.T311"), QStringLiteral("Text: Meryl Demon's Pick")},
    {QStringLiteral("ITEM.T312"), QStringLiteral("Text: Meryl Harvine's Flute")},
    {QStringLiteral("ITEM.T313"), QStringLiteral("Text: Meryl Ground Bell")},
    {QStringLiteral("ITEM.T314"), QStringLiteral("Text: Meryl Fire Crystal")},
    {QStringLiteral("ITEM.T315"), QStringLiteral("Text: Meryl Water Crystal")},
    {QStringLiteral("ITEM.T316"), QStringLiteral("Text: Meryl Earth Crystal")},
    {QStringLiteral("ITEM.T317"), QStringLiteral("Text: Meryl Wind Crystal")},
    {QStringLiteral("ITEM.T318"), QStringLiteral("Text: Meryl Light Crystal")},
    {QStringLiteral("ITEM.T319"), QStringLiteral("Text: Meryl Dark Crystal")},
    {QStringLiteral("ITEM.T320"), QStringLiteral("Text: Meryl Crystal")},
    {QStringLiteral("ITEM.T321"), QStringLiteral("Text: Meryl Crystal Shard")},
    {QStringLiteral("ITEM.T322"), QStringLiteral("Text: Meryl Elf's Key")},
    {QStringLiteral("ITEM.T323"), QStringLiteral("Text: Meryl Pirates Key")},
    {QStringLiteral("ITEM.T324"), QStringLiteral("Text: Meryl Skull Key")},
    {QStringLiteral("ITEM.T325"), QStringLiteral("Text: Meryl Jail Key")},
    {QStringLiteral("ITEM.T326"), QStringLiteral("Text: Meryl Rhombus Key")},
    {QStringLiteral("ITEM.T327"), QStringLiteral("Text: Meryl Harvine's Key")},
    {QStringLiteral("ITEM.T328"), QStringLiteral("Text: Meryl Dragon Stone")},
    {QStringLiteral("ITEM.T329"), QStringLiteral("Text: Meryl Magician's Key")},
    {QStringLiteral("ITEM.T330"), QStringLiteral("Text: Meryl Silver Key")},
    {QStringLiteral("ITEM.T331"), QStringLiteral("Text: Meryl Gold Key")},
    {QStringLiteral("ITEM.T332"), QStringLiteral("Text: Meryl Shrine Key")},
    {QStringLiteral("ITEM.T333"), QStringLiteral("Text: Meryl Moon Gate")},
    {QStringLiteral("ITEM.T334"), QStringLiteral("Text: Meryl Star Gate")},
    {QStringLiteral("ITEM.T335"), QStringLiteral("Text: Meryl Sun Gate")},
    {QStringLiteral("ITEM.T336"), QStringLiteral("Text: Meryl Moon Key")},
    {QStringLiteral("ITEM.T337"), QStringLiteral("Text: Meryl Star Key")},
    {QStringLiteral("ITEM.T338"), QStringLiteral("Text: Meryl Sun Key")},
    {QStringLiteral("ITEM.T339"), QStringLiteral("Text: Meryl Arrow For The Bow")},
    {QStringLiteral("ITEM.T340"), QStringLiteral("Text: Meryl Elf's Bolt")},
    {QStringLiteral("ITEM.T365"), QStringLiteral("Text: Truth Glass West Seaside")},
    {QStringLiteral("ITEM.T366"), QStringLiteral("Text: Truth Glass The Pirate's Cave")},
    {QStringLiteral("ITEM.T367"), QStringLiteral("Text: Truth Glass Cave Of Old Hand")},
    {QStringLiteral("ITEM.T368"), QStringLiteral("Text: Truth Glass The Mage's Lighthouse")},
    {QStringLiteral("ITEM.T369"), QStringLiteral("Text: Truth Glass The North Village")},
    {QStringLiteral("ITEM.T370"), QStringLiteral("Text: Truth Glass The South Village")},
    {QStringLiteral("ITEM.T371"), QStringLiteral("Text: Truth Glass ASmall Mine")},
    {QStringLiteral("ITEM.T372"), QStringLiteral("Text: Truth Glass The North Graveyard")},
    {QStringLiteral("ITEM.T373"), QStringLiteral("Text: Truth Glass Base No 1")},
    {QStringLiteral("ITEM.T374"), QStringLiteral("Text: Truth Glass Base No 2")},
    {QStringLiteral("ITEM.T375"), QStringLiteral("Text: Truth Glass Base No 3")},
    {QStringLiteral("ITEM.T376"), QStringLiteral("Text: Truth Glass Base No 4")},
    {QStringLiteral("ITEM.T377"), QStringLiteral("Text: Truth Glass Base No 5")},
    {QStringLiteral("ITEM.T378"), QStringLiteral("Text: Truth Glass Base No 6")},
    {QStringLiteral("ITEM.T379"),
     QStringLiteral("Text: Truth Glass The Ruins Of King Harvine's Castle")},
    {QStringLiteral("ITEM.T380"), QStringLiteral("Text: Truth Glass The Termite's Nest")},
    {QStringLiteral("ITEM.T381"), QStringLiteral("Text: Truth Glass The Cemetery")},
    {QStringLiteral("ITEM.T382"), QStringLiteral("Text: Truth Glass The Soldier's Cemetery")},
    {QStringLiteral("ITEM.T383"), QStringLiteral("Text: Truth Glass The Window Of Homesickness")},
    {QStringLiteral("ITEM.T384"), QStringLiteral("Text: Truth Glass The Elf Graveyard")},
    {QStringLiteral("ITEM.T385"), QStringLiteral("Text: Truth Glass The East Village")},
    {QStringLiteral("ITEM.T386"), QStringLiteral("Text: Truth Glass The Elf Shrine")},
    {QStringLiteral("ITEM.T387"), QStringLiteral("Text: Truth Glass Seath's Fountain")},
    {QStringLiteral("ITEM.T388"), QStringLiteral("Text: Truth Glass The Magic Palace Of Fire")},
    {QStringLiteral("ITEM.T389"), QStringLiteral("Text: Truth Glass The Magic Palace Of Ice")},
    {QStringLiteral("ITEM.T390"), QStringLiteral("Text: Truth Glass The Demon's Grave")},
    {QStringLiteral("ITEM.T391"), QStringLiteral("Text: Truth Glass The South Graveyard")},
    {QStringLiteral("ITEM.T392"), QStringLiteral("Text: Truth Glass The Big Mine")},
    {QStringLiteral("ITEM.T393"), QStringLiteral("Text: Truth Glass The Poisoned Cave")},
    {QStringLiteral("ITEM.T394"), QStringLiteral("Text: Truth Glass The Cave Of The Darkside")},
    {QStringLiteral("ITEM.T395"), QStringLiteral("Text: Truth Glass The Elf Cave")},
    {QStringLiteral("ITEM.T396"), QStringLiteral("Text: Truth Glass The Cave Of The Earth Soul")},
    {QStringLiteral("ITEM.T397"), QStringLiteral("Text: Truth Glass The Lookout")},
    {QStringLiteral("ITEM.T398"), QStringLiteral("Text: Truth Glass Necron's Coliseum")},
    {QStringLiteral("ITEM.T399"), QStringLiteral("Text: Truth Glass The Warriors Graveyard")},
    {QStringLiteral("ITEM.T400"), QStringLiteral("Text: Truth Glass The Research Office")},
    {QStringLiteral("ITEM.T401"), QStringLiteral("Text: Truth Glass The Village Of The Wind")},
    {QStringLiteral("ITEM.T402"), QStringLiteral("Text: Truth Glass The East Seaside")},

    {QStringLiteral("MO.T0"), QStringLiteral("Slime")},
    {QStringLiteral("MO.T1"), QStringLiteral("Poison Slime")},
    {QStringLiteral("MO.T2"), QStringLiteral("Sigill")},
    {QStringLiteral("MO.T3"), QStringLiteral("Baltail (Body)")},
    {QStringLiteral("MO.T4"), QStringLiteral("Baltail (Tail)")},
    {QStringLiteral("MO.T5"), QStringLiteral("Sting Fly (Body)")},
    {QStringLiteral("MO.T6"), QStringLiteral("Sting Fly (Tail)")},
    {QStringLiteral("MO.T7"), QStringLiteral("Fire Elemental")},
    {QStringLiteral("MO.T8"), QStringLiteral("Ghost")},
    {QStringLiteral("MO.T9"), QStringLiteral("Reik")},
    {QStringLiteral("MO.T10"), QStringLiteral("Slime")},
    {QStringLiteral("MO.T11"), QStringLiteral("Slime")},
    {QStringLiteral("MO.T12"), QStringLiteral("Head Eater")},
    {QStringLiteral("MO.T13"), QStringLiteral("Mogle")},
    {QStringLiteral("MO.T14"), QStringLiteral("S-Knight")},
    {QStringLiteral("MO.T15"), QStringLiteral("Necron's Soldier")},
    {QStringLiteral("MO.T16"), QStringLiteral("Archer")},
    {QStringLiteral("MO.T17"), QStringLiteral("Slime")},
    {QStringLiteral("MO.T18"), QStringLiteral("Skeleton")},
    {QStringLiteral("MO.T19"), QStringLiteral("Termite")},
    {QStringLiteral("MO.T20"), QStringLiteral("Kald")},
    {QStringLiteral("MO.T21"), QStringLiteral("Psythe")},
    {QStringLiteral("MO.T22"), QStringLiteral("Termite Queen")},
    {QStringLiteral("MO.T23"), QStringLiteral("Spike Ball (trap)")},
    {QStringLiteral("MO.T24"), QStringLiteral("Log Stalker")},
    {QStringLiteral("MO.T25"), QStringLiteral("Demon Lord")},
    {QStringLiteral("MO.T26"), QStringLiteral("Kraken (Body)")},
    {QStringLiteral("MO.T27"), QStringLiteral("Kraken (Shell)")},
    {QStringLiteral("MO.T28"), QStringLiteral("Earth Elemental")},
    {QStringLiteral("MO.T29"), QStringLiteral("Refma")},
    {QStringLiteral("MO.T30"), QStringLiteral("Tarn")},
    {QStringLiteral("MO.T31"), QStringLiteral("Copper Knight")},
    {QStringLiteral("MO.T32"), QStringLiteral("Necron")},
    {QStringLiteral("MO.T33"), QStringLiteral("Slime")},
    {QStringLiteral("MO.T34"), QStringLiteral("Slime")},
    {QStringLiteral("MO.T35"), QStringLiteral("Slime")},
    {QStringLiteral("MO.T36"), QStringLiteral("Guyra")},
    {QStringLiteral("MO.T37"), QStringLiteral("Salamander")},
    {QStringLiteral("MO.T38"), QStringLiteral("Flame Spirit")},
    {QStringLiteral("MO.T39"), QStringLiteral("Billent")},
    {QStringLiteral("MO.T40"), QStringLiteral("Slime")},
    {QStringLiteral("MO.T41"), QStringLiteral("Skeleton of One Eyed Giant")},
    {QStringLiteral("MO.T42"), QStringLiteral("Picture of a King")},
    {QStringLiteral("MO.T43"), QStringLiteral("Mecha Demon Lord")},
    {QStringLiteral("MO.T44"), QStringLiteral("Mecha Termite")},
    {QStringLiteral("MO.T45"), QStringLiteral("Mecha Reik")},
    {QStringLiteral("MO.T46"), QStringLiteral("Magician's Lamp")},
    {QStringLiteral("MO.T47"), QStringLiteral("Bitt")},
    {QStringLiteral("MO.T48"), QStringLiteral("Refma")},
    {QStringLiteral("MO.T49"), QStringLiteral("Cellfy Foss")},
    {QStringLiteral("MO.T50"), QStringLiteral("Cellfy Foss")},
    {QStringLiteral("MO.T51"), QStringLiteral("Raffy Foss")},
    {QStringLiteral("MO.T52"), QStringLiteral("Jose Harven")},
    {QStringLiteral("MO.T53"), QStringLiteral("Nola Bagil")},
    {QStringLiteral("MO.T54"), QStringLiteral("Meryl")},
    {QStringLiteral("MO.T55"), QStringLiteral("Gigi Budwell")},
    {QStringLiteral("MO.T56"), QStringLiteral("Gigi Budwell (Watering)")},
    {QStringLiteral("MO.T57"), QStringLiteral("Teo Budwell")},
    {QStringLiteral("MO.T58"), QStringLiteral("Teo Budwell (With Gigi)")},
    {QStringLiteral("MO.T59"), QStringLiteral("Teo Budwell (Mowing)")},
    {QStringLiteral("MO.T60"), QStringLiteral("Karen Shore")},
    {QStringLiteral("MO.T61"), QStringLiteral("Leon Shore")},
    {QStringLiteral("MO.T62"), QStringLiteral("Leon Shore (Watering)")},
    {QStringLiteral("MO.T63"), QStringLiteral("Al Hunt")},
    {QStringLiteral("MO.T64"), QStringLiteral("Harris Carvitto")},
    {QStringLiteral("MO.T65"), QStringLiteral("Fai Fadlin")},
    {QStringLiteral("MO.T66"), QStringLiteral("Cliff Lore")},
    {QStringLiteral("MO.T67"), QStringLiteral("Rand Ferrer")},
    {QStringLiteral("MO.T68"), QStringLiteral("David Tabler")},
    {QStringLiteral("MO.T69"), QStringLiteral("Dalf Vice")},
    {QStringLiteral("MO.T70"), QStringLiteral("Radd Bilheim")},
    {QStringLiteral("MO.T71"), QStringLiteral("Krola Amgun")},
    {QStringLiteral("MO.T72"), QStringLiteral("Krola Amgun (Cooking)")},
    {QStringLiteral("MO.T73"), QStringLiteral("Sandler Amgun")},
    {QStringLiteral("MO.T74"), QStringLiteral("Sandler Amgun")},
    {QStringLiteral("MO.T75"), QStringLiteral("Mark Wozz")},
    {QStringLiteral("MO.T76"), QStringLiteral("Earnest Clyde")},
    {QStringLiteral("MO.T77"), QStringLiteral("Kehl Hunt")},
    {QStringLiteral("MO.T78"), QStringLiteral("Kehl Hunt")},
    {QStringLiteral("MO.T79"), QStringLiteral("Karen Shore (Chair)")},
    {QStringLiteral("MO.T80"), QStringLiteral("Jose Haven (Death)")},
    {QStringLiteral("MO.T81"), QStringLiteral("Saint Grave")},
    {QStringLiteral("MO.T82"), QStringLiteral("Earnest Clyde (Sitting)")},
    {QStringLiteral("MO.T83"), QStringLiteral("Dragon Grass")},
    {QStringLiteral("MO.T84"), QStringLiteral("Jose Haven (Death)")},
    {QStringLiteral("MO.T85"), QStringLiteral("Miria")},
    {QStringLiteral("MO.T86"), QStringLiteral("Dagger")},
    {QStringLiteral("MO.T87"), QStringLiteral("Short Sword")},
    {QStringLiteral("MO.T88"), QStringLiteral("Knight Sword")},
    {QStringLiteral("MO.T89"), QStringLiteral("Morning Star")},
    {QStringLiteral("MO.T90"), QStringLiteral("Battle Hammer")},
    {QStringLiteral("MO.T91"), QStringLiteral("Bastard Sword")},
    {QStringLiteral("MO.T92"), QStringLiteral("Crescent Axe")},
    {QStringLiteral("MO.T93"), QStringLiteral("Default Model")},
    {QStringLiteral("MO.T94"), QStringLiteral("Seath's Sword (And Wall)")},
    {QStringLiteral("MO.T95"), QStringLiteral("Flame Sword")},
    {QStringLiteral("MO.T96"), QStringLiteral("Shiden")},
    {QStringLiteral("MO.T97"), QStringLiteral("Spider")},
    {QStringLiteral("MO.T98"), QStringLiteral("Ice Blade")},
    {QStringLiteral("MO.T99"), QStringLiteral("Seath's Sword")},
    {QStringLiteral("MO.T100"), QStringLiteral("Moonlight Sword")},
    {QStringLiteral("MO.T101"), QStringLiteral("Dark Slayer")},
    {QStringLiteral("MO.T102"), QStringLiteral("Bow")},
    {QStringLiteral("MO.T103"), QStringLiteral("Arbalest")},
    {QStringLiteral("MO.T104"), QStringLiteral("Seath's Sword (Broken)")},
    {QStringLiteral("MO.T105"), QStringLiteral("Default Model")},
    {QStringLiteral("MO.T106"), QStringLiteral("Default Model")},
    {QStringLiteral("MO.T107"), QStringLiteral("Iron Mask")},
    {QStringLiteral("MO.T108"), QStringLiteral("Knight Helm")},
    {QStringLiteral("MO.T109"), QStringLiteral("Great Helm")},
    {QStringLiteral("MO.T110"), QStringLiteral("Blood Crown")},
    {QStringLiteral("MO.T111"), QStringLiteral("Lightning Helm")},
    {QStringLiteral("MO.T112"), QStringLiteral("Seath's Helm")},
    {QStringLiteral("MO.T113"), QStringLiteral("Default Model")},

    {QStringLiteral("RTIM.T0"), QStringLiteral("Western Shore Texture Database")},
    {QStringLiteral("RTIM.T1"), QStringLiteral("Garrison Texture Database")},
    {QStringLiteral("RTIM.T2"), QStringLiteral("Central Village Texture Database")},
    {QStringLiteral("RTIM.T3"), QStringLiteral("East Village Texture Database")},
    {QStringLiteral("RTIM.T4"), QStringLiteral("Cathedral Texture Database")},
    {QStringLiteral("RTIM.T5"), QStringLiteral("Big Mine Texture Database")},
    {QStringLiteral("RTIM.T6"), QStringLiteral("Necron's Coliseum Texture Database")},
    {QStringLiteral("RTIM.T7"), QStringLiteral("Guyra's Lair Texture Database")},
    {QStringLiteral("RTIM.T8"), QStringLiteral("Weird Debug Map Texture Database")},
    {QStringLiteral("RTIM.T16"), QStringLiteral("Picture of a King")},
    {QStringLiteral("RTIM.T23"), QStringLiteral("Village House 01")},
    {QStringLiteral("RTIM.T24"), QStringLiteral("Village House 02")},
    {QStringLiteral("RTIM.T28"), QStringLiteral("Seath's Door")},
    {QStringLiteral("RTIM.T29"), QStringLiteral("The Picture of Warriors")},
    {QStringLiteral("RTIM.T65"), QStringLiteral("Seath's Floor and Door")},

    {QStringLiteral("RTMD.T0"), QStringLiteral("Western Shore Tileset")},
    {QStringLiteral("RTMD.T1"), QStringLiteral("Garrison Tileset")},
    {QStringLiteral("RTMD.T2"), QStringLiteral("Central Village Tileset")},
    {QStringLiteral("RTMD.T3"), QStringLiteral("East Village Tileset")},
    {QStringLiteral("RTMD.T4"), QStringLiteral("Cathedral Tileset")},
    {QStringLiteral("RTMD.T5"), QStringLiteral("Big Mine Tileset")},
    {QStringLiteral("RTMD.T6"), QStringLiteral("Necron's Coliseum Tileset")},
    {QStringLiteral("RTMD.T7"), QStringLiteral("Guyra's Lair Tileset")},
    {QStringLiteral("RTMD.T8"), QStringLiteral("Weird Debug Map Tileset")},

    {QStringLiteral("TALK.T58"), QStringLiteral("Jose Harven Dialogue 1")},
    {QStringLiteral("TALK.T59"), QStringLiteral("Jose Harven Dialogue 2")},
    {QStringLiteral("TALK.T60"), QStringLiteral("Jose Harven Dialogue 3")},
    {QStringLiteral("TALK.T61"), QStringLiteral("Jose Harven Dialogue 4")},
    {QStringLiteral("TALK.T62"), QStringLiteral("Jose Harven Dialogue 5")},
    {QStringLiteral("TALK.T63"), QStringLiteral("Jose Harven Dialogue 6")},
    {QStringLiteral("TALK.T64"), QStringLiteral("Jose Harven Dialogue 7")},

    {QStringLiteral("VAB.T1"), QStringLiteral("Sound Effects Waveforms")},
    {QStringLiteral("VAB.T112"), QStringLiteral("Western Shore Sequence")},
    {QStringLiteral("VAB.T113"), QStringLiteral("Garrison Sequence")},
    {QStringLiteral("VAB.T114"), QStringLiteral("Central Village Sequence")},
    {QStringLiteral("VAB.T115"), QStringLiteral("East Village Sequence")},
    {QStringLiteral("VAB.T116"), QStringLiteral("Cathedral Sequence")},
    {QStringLiteral("VAB.T117"), QStringLiteral("Big Mine Sequence")},
    {QStringLiteral("VAB.T118"), QStringLiteral("Necrons Coliseum Sequence")},
    {QStringLiteral("VAB.T119"), QStringLiteral("Guyras Lair Sequence")},
    {QStringLiteral("VAB.T121"), QStringLiteral("Central Village 2 Sequence")},
};
} // namespace PrettyNames
