#include "object.h"
#include "core/kfmtcore.h"

QString KF2::getObjectClassTypeName(const KF2::ObjectClassType classType)
{
    switch (classType)
    {
        case ObjectClassType::DragonGrass: return QStringLiteral("Dragon Grass");
        case ObjectClassType::DragonStoneSlot: return QStringLiteral("Dragon Stone Slot");
        case ObjectClassType::FloorTrap: return QStringLiteral("Floor Trap");
        case ObjectClassType::GuidePost: return QStringLiteral("Guide Post");
        case ObjectClassType::GuyraWarp: return QStringLiteral("Guyra Warp");
        case ObjectClassType::Hider: return QStringLiteral("Hider");
        case ObjectClassType::LoadTrigger: return QStringLiteral("LoadTrigger");
        case ObjectClassType::Minecart: return QStringLiteral("Minecart");
        case ObjectClassType::None: return QStringLiteral("None");
        case ObjectClassType::PickableItem: return QStringLiteral("Pickable Item");
        case ObjectClassType::RhombusKeySlot: return QStringLiteral("Rhombus Key Slot");
        case ObjectClassType::RotatesToOpen: return QStringLiteral("Rotates to Open");
        case ObjectClassType::SavePoint: return QStringLiteral("Save Point");
        case ObjectClassType::SecretCompartment: return QStringLiteral("Secret Compartment");
        case ObjectClassType::ShrineKeySlot: return QStringLiteral("Shrine Key Slot");
        case ObjectClassType::Sign: return QStringLiteral("Sign");
        case ObjectClassType::SkullKeySlot: return QStringLiteral("Skull Key Slot");
        case ObjectClassType::Skybox: return QStringLiteral("Skybox");
        case ObjectClassType::SlidesToOpen: return QStringLiteral("Slides to Open");
        case ObjectClassType::Switch: return QStringLiteral("Switch");
        case ObjectClassType::Trap: return QStringLiteral("Trap");
        case ObjectClassType::VerticalDoor: return QStringLiteral("Vertical Door");
        case ObjectClassType::VerticalDoor2: return QStringLiteral("Vertical Door 2");
        case ObjectClassType::WaterWell: return QStringLiteral("Water Well");
        default: return unknownString;
    }
}

QString KF2::getObjectName(const KF2::ObjectID itemId)
{
    switch (itemId)
    {
        case ObjectID::ABrokenSword: return QStringLiteral("ABrokenSword");
        case ObjectID::ASoldierOfVerdite: return QStringLiteral("ASoldierOfVerdite");
        case ObjectID::ArmsA: return QStringLiteral("ArmsA");
        case ObjectID::ArmsDemonsHands: return QStringLiteral("ArmsDemonsHands");
        case ObjectID::ArmsIronGloves: return QStringLiteral("ArmsIronGloves");
        case ObjectID::ArmsRuinousGloves: return QStringLiteral("ArmsRuinousGloves");
        case ObjectID::ArmsSilverArms: return QStringLiteral("ArmsSilverArms");
        case ObjectID::ArmsStoneHands: return QStringLiteral("ArmsStoneHands");
        case ObjectID::Barrel: return QStringLiteral("Barrel");
        case ObjectID::Bed: return QStringLiteral("Bed");
        case ObjectID::BigGreyDoorLeft: return QStringLiteral("BigGreyDoorLeft");
        case ObjectID::BigGreyDoorRight: return QStringLiteral("BigGreyDoorRight");
        case ObjectID::BigRoughStoneDoor: return QStringLiteral("BigRoughStoneDoor");
        case ObjectID::BigStoneDoor: return QStringLiteral("BigStoneDoor");
        case ObjectID::BodyA: return QStringLiteral("BodyA");
        case ObjectID::BodyBreastPlate: return QStringLiteral("BodyBreastPlate");
        case ObjectID::BodyDarkArmor: return QStringLiteral("BodyDarkArmor");
        case ObjectID::BodyIceArmor: return QStringLiteral("BodyIceArmor");
        case ObjectID::BodyKnightPlate: return QStringLiteral("BodyKnightPlate");
        case ObjectID::BodySeathsArmor: return QStringLiteral("BodySeathsArmor");
        case ObjectID::Bones: return QStringLiteral("Bones");
        case ObjectID::Bones2: return QStringLiteral("Bones2");
        case ObjectID::Bucket: return QStringLiteral("Bucket");
        case ObjectID::CeilingTorch: return QStringLiteral("CeilingTorch");
        case ObjectID::Chair: return QStringLiteral("Chair");
        case ObjectID::ColosseumDoor: return QStringLiteral("ColosseumDoor");
        case ObjectID::CopperKnightStatue: return QStringLiteral("CopperKnightStatue");
        case ObjectID::CrossFeetTable: return QStringLiteral("CrossFeetTable");
        case ObjectID::DaytimeSkybox: return QStringLiteral("DaytimeSkybox");
        case ObjectID::DeadCrystalMiner: return QStringLiteral("DeadCrystalMiner");
        case ObjectID::DeadDudeRENAME_ME: return QStringLiteral("DeadDudeRENAME_ME");
        case ObjectID::DemonLordFromMadScientistTube:
            return QStringLiteral("DemonLordFromMadScientistTube");
        case ObjectID::DemonLordStatue: return QStringLiteral("DemonLordStatue");
        case ObjectID::DragonGrass: return QStringLiteral("DragonGrass");
        case ObjectID::DragonStoneSlot: return QStringLiteral("DragonStoneSlot");
        case ObjectID::DrawbridgeSwitch: return QStringLiteral("DrawbridgeSwitch");
        case ObjectID::DummyItem1: return QStringLiteral("DummyItem1");
        case ObjectID::DummyItem2: return QStringLiteral("DummyItem2");
        case ObjectID::DummyItem3: return QStringLiteral("DummyItem3");
        case ObjectID::DummyItem4: return QStringLiteral("DummyItem4");
        case ObjectID::DummyItem5: return QStringLiteral("DummyItem5");
        case ObjectID::DummyItem6: return QStringLiteral("DummyItem6");
        case ObjectID::DummyItem7: return QStringLiteral("DummyItem7");
        case ObjectID::EarthElementalStatue: return QStringLiteral("EarthElementalStatue");
        case ObjectID::ElfsGrave: return QStringLiteral("ElfsGrave");
        case ObjectID::EquipItemAmuletOfMist: return QStringLiteral("EquipItemAmuletOfMist");
        case ObjectID::EquipItemEarthRing: return QStringLiteral("EquipItemEarthRing");
        case ObjectID::EquipItemLightwaveRing: return QStringLiteral("EquipItemLightwaveRing");
        case ObjectID::EquipItemPsycprosCollar: return QStringLiteral("EquipItemPsycprosCollar");
        case ObjectID::EquipItemScorpionsBracelet:
            return QStringLiteral("EquipItemScorpionsBracelet");
        case ObjectID::EquipItemSeathsBracelet: return QStringLiteral("EquipItemSeathsBracelet");
        case ObjectID::EquipItemSeathsTear: return QStringLiteral("EquipItemSeathsTear");
        case ObjectID::FeetA: return QStringLiteral("FeetA");
        case ObjectID::FeetDeathWalkers: return QStringLiteral("FeetDeathWalkers");
        case ObjectID::FeetIronBoots: return QStringLiteral("FeetIronBoots");
        case ObjectID::FeetLegGuarders: return QStringLiteral("FeetLegGuarders");
        case ObjectID::FeetRuinousBoots: return QStringLiteral("FeetRuinousBoots");
        case ObjectID::FeetSilverBoots: return QStringLiteral("FeetSilverBoots");
        case ObjectID::GoldenThingRENAME_ME: return QStringLiteral("GoldenThingRENAME_ME");
        case ObjectID::GreenWallFloorTrap: return QStringLiteral("GreenWallFloorTrap");
        case ObjectID::GreenWallSecretDoor: return QStringLiteral("GreenWallSecretDoor");
        case ObjectID::GreenWallWithSecret1: return QStringLiteral("GreenWallWithSecret1");
        case ObjectID::GreenWallWithSecret2: return QStringLiteral("GreenWallWithSecret2");
        case ObjectID::GreenWallWithSpikeTrap: return QStringLiteral("GreenWallWithSpikeTrap");
        case ObjectID::Guidepost: return QStringLiteral("Guidepost");
        case ObjectID::GuyraTeleportCube: return QStringLiteral("GuyraTeleportCube");
        case ObjectID::HarvineCastleSign: return QStringLiteral("HarvineCastleSign");
        case ObjectID::HarvinesCastleDoor: return QStringLiteral("HarvinesCastleDoor");
        case ObjectID::HarvinesThrone: return QStringLiteral("HarvinesThrone");
        case ObjectID::HeadA: return QStringLiteral("HeadA");
        case ObjectID::HeadBloodCrown: return QStringLiteral("HeadBloodCrown");
        case ObjectID::HeadGreatHelm: return QStringLiteral("HeadGreatHelm");
        case ObjectID::HeadIronMask: return QStringLiteral("HeadIronMask");
        case ObjectID::HeadKnightHelm: return QStringLiteral("HeadKnightHelm");
        case ObjectID::HeadLightningHelm: return QStringLiteral("HeadLightningHelm");
        case ObjectID::HeadSeathsHelm: return QStringLiteral("HeadSeathsHelm");
        case ObjectID::InvisibleObject: return QStringLiteral("InvisibleObject");
        case ObjectID::ItemAHerb: return QStringLiteral("ItemAHerb");
        case ObjectID::ItemAHerb2: return QStringLiteral("ItemAHerb2");
        case ObjectID::ItemAPotion: return QStringLiteral("ItemAPotion");
        case ObjectID::ItemARing: return QStringLiteral("ItemARing");
        case ObjectID::ItemAntidote: return QStringLiteral("ItemAntidote");
        case ObjectID::ItemArrowForTheBow: return QStringLiteral("ItemArrowForTheBow");
        case ObjectID::ItemBloodStone: return QStringLiteral("ItemBloodStone");
        case ObjectID::ItemBluePotion: return QStringLiteral("ItemBluePotion");
        case ObjectID::ItemCrystal: return QStringLiteral("ItemCrystal");
        case ObjectID::ItemCrystalFlask: return QStringLiteral("ItemCrystalFlask");
        case ObjectID::ItemCrystalShard: return QStringLiteral("ItemCrystalShard");
        case ObjectID::ItemDarkCrystal: return QStringLiteral("ItemDarkCrystal");
        case ObjectID::ItemDemonsPick: return QStringLiteral("ItemDemonsPick");
        case ObjectID::ItemDragonCrystal: return QStringLiteral("ItemDragonCrystal");
        case ObjectID::ItemDragonStone: return QStringLiteral("ItemDragonStone");
        case ObjectID::ItemEarthCrystal: return QStringLiteral("ItemEarthCrystal");
        case ObjectID::ItemEarthHerb: return QStringLiteral("ItemEarthHerb");
        case ObjectID::ItemElfsBolt: return QStringLiteral("ItemElfsBolt");
        case ObjectID::ItemElfsKey: return QStringLiteral("ItemElfsKey");
        case ObjectID::ItemFigureOfSeath: return QStringLiteral("ItemFigureOfSeath");
        case ObjectID::ItemFireCrystal: return QStringLiteral("ItemFireCrystal");
        case ObjectID::ItemGoldCoin: return QStringLiteral("ItemGoldCoin");
        case ObjectID::ItemGoldKey: return QStringLiteral("ItemGoldKey");
        case ObjectID::ItemGoldPotion: return QStringLiteral("ItemGoldPotion");
        case ObjectID::ItemGreenPotion: return QStringLiteral("ItemGreenPotion");
        case ObjectID::ItemGroundBell: return QStringLiteral("ItemGroundBell");
        case ObjectID::ItemHarvinesFlute: return QStringLiteral("ItemHarvinesFlute");
        case ObjectID::ItemHarvinesKey: return QStringLiteral("ItemHarvinesKey");
        case ObjectID::ItemJailKey: return QStringLiteral("ItemJailKey");
        case ObjectID::ItemLightCrystal: return QStringLiteral("ItemLightCrystal");
        case ObjectID::ItemMagiciansKey: return QStringLiteral("ItemMagiciansKey");
        case ObjectID::ItemMinersMap: return QStringLiteral("ItemMinersMap");
        case ObjectID::ItemMoonGate: return QStringLiteral("ItemMoonGate");
        case ObjectID::ItemMoonKey: return QStringLiteral("ItemMoonKey");
        case ObjectID::ItemMoonStone: return QStringLiteral("ItemMoonStone");
        case ObjectID::ItemNecronsMap: return QStringLiteral("ItemNecronsMap");
        case ObjectID::ItemPhantomRod: return QStringLiteral("ItemPhantomRod");
        case ObjectID::ItemPiratesKey: return QStringLiteral("ItemPiratesKey");
        case ObjectID::ItemPiratesMap: return QStringLiteral("ItemPiratesMap");
        case ObjectID::ItemRedPotion: return QStringLiteral("ItemRedPotion");
        case ObjectID::ItemRhombusKey: return QStringLiteral("ItemRhombusKey");
        case ObjectID::ItemSeathsPlume: return QStringLiteral("ItemSeathsPlume");
        case ObjectID::ItemShrineKey: return QStringLiteral("ItemShrineKey");
        case ObjectID::ItemSilverKey: return QStringLiteral("ItemSilverKey");
        case ObjectID::ItemSkullKey: return QStringLiteral("ItemSkullKey");
        case ObjectID::ItemStarGate: return QStringLiteral("ItemStarGate");
        case ObjectID::ItemStarKey: return QStringLiteral("ItemStarKey");
        case ObjectID::ItemSunGate: return QStringLiteral("ItemSunGate");
        case ObjectID::ItemSunKey: return QStringLiteral("ItemSunKey");
        case ObjectID::ItemTruthGlass: return QStringLiteral("ItemTruthGlass");
        case ObjectID::ItemVerdite: return QStringLiteral("ItemVerdite");
        case ObjectID::ItemWaterCrystal: return QStringLiteral("ItemWaterCrystal");
        case ObjectID::ItemWindCrystal: return QStringLiteral("ItemWindCrystal");
        case ObjectID::JailDoor: return QStringLiteral("JailDoor");
        case ObjectID::KnockerDoorLeft: return QStringLiteral("KnockerDoorLeft");
        case ObjectID::KnockerDoorRight: return QStringLiteral("KnockerDoorRight");
        case ObjectID::Lantern: return QStringLiteral("Lantern");
        case ObjectID::LoadArea: return QStringLiteral("LoadArea");
        case ObjectID::MadScientistBox: return QStringLiteral("MadScientistBox");
        case ObjectID::MadScientistLightCrystalMachine:
            return QStringLiteral("MadScientistLightCrystalMachine");
        case ObjectID::MadScientistTube: return QStringLiteral("MadScientistTube");
        case ObjectID::MarbleWallFloorTrap: return QStringLiteral("MarbleWallFloorTrap");
        case ObjectID::MineSign: return QStringLiteral("MineSign");
        case ObjectID::Minecart: return QStringLiteral("Minecart");
        case ObjectID::MinersGraveMaybe: return QStringLiteral("MinersGraveMaybe");
        case ObjectID::Moon: return QStringLiteral("Moon");
        case ObjectID::MountainSkybox: return QStringLiteral("MountainSkybox");
        case ObjectID::NighttimeSkybox: return QStringLiteral("NighttimeSkybox");
        case ObjectID::NighttimeSkybox2: return QStringLiteral("NighttimeSkybox2");
        case ObjectID::None: return QStringLiteral("None");
        case ObjectID::PillarOfWind: return QStringLiteral("PillarOfWind");
        case ObjectID::RedFlower: return QStringLiteral("RedFlower");
        case ObjectID::RhombusKeyDoor: return QStringLiteral("RhombusKeyDoor");
        case ObjectID::RhombusKeySlot: return QStringLiteral("RhombusKeySlot");
        case ObjectID::SamuraisGrave: return QStringLiteral("SamuraisGrave");
        case ObjectID::Savepoint: return QStringLiteral("Savepoint");
        case ObjectID::SeathsFountainDoorLeft: return QStringLiteral("SeathsFountainDoorLeft");
        case ObjectID::SeathsFountainDoorRight: return QStringLiteral("SeathsFountainDoorRight");
        case ObjectID::SeathsFountainPillar: return QStringLiteral("SeathsFountainPillar");
        case ObjectID::SecretDoor: return QStringLiteral("SecretDoor");
        case ObjectID::Shelf: return QStringLiteral("Shelf");
        case ObjectID::ShieldA: return QStringLiteral("ShieldA");
        case ObjectID::ShieldCrystalGuard: return QStringLiteral("ShieldCrystalGuard");
        case ObjectID::ShieldLargeShield: return QStringLiteral("ShieldLargeShield");
        case ObjectID::ShieldLeatherShield: return QStringLiteral("ShieldLeatherShield");
        case ObjectID::ShieldMoonGuard: return QStringLiteral("ShieldMoonGuard");
        case ObjectID::ShieldSeathsShield: return QStringLiteral("ShieldSeathsShield");
        case ObjectID::ShieldSkullShield: return QStringLiteral("ShieldSkullShield");
        case ObjectID::ShovelAndHammer: return QStringLiteral("ShovelAndHammer");
        case ObjectID::ShrineKeySlot: return QStringLiteral("ShrineKeySlot");
        case ObjectID::Sign: return QStringLiteral("Sign");
        case ObjectID::SimpleStoolMaybeRENAME_ME:
            return QStringLiteral("SimpleStoolMaybeRENAME_ME");
        case ObjectID::SkullKeySlot: return QStringLiteral("SkullKeySlot");
        case ObjectID::SkullKeyWaterObstacle: return QStringLiteral("SkullKeyWaterObstacle");
        case ObjectID::SlotForSomethingRENAME_ME:
            return QStringLiteral("SlotForSomethingRENAME_ME");
        case ObjectID::SmallBed: return QStringLiteral("SmallBed");
        case ObjectID::SmallStackOfLogs: return QStringLiteral("SmallStackOfLogs");
        case ObjectID::SmallTable: return QStringLiteral("SmallTable");
        case ObjectID::SmallWeirdPillarRENAME_ME:
            return QStringLiteral("SmallWeirdPillarRENAME_ME");
        case ObjectID::SomeBrokenGrave: return QStringLiteral("SomeBrokenGrave");
        case ObjectID::SomeBrokenGrave2: return QStringLiteral("SomeBrokenGrave2");
        case ObjectID::SomeDoorHandleRENAME_ME: return QStringLiteral("SomeDoorHandleRENAME_ME");
        case ObjectID::SomeGrave: return QStringLiteral("SomeGrave");
        case ObjectID::SquareWell: return QStringLiteral("SquareWell");
        case ObjectID::StoneChestBody: return QStringLiteral("StoneChestBody");
        case ObjectID::StoneChestLid: return QStringLiteral("StoneChestLid");
        case ObjectID::StoneGobletWithLavaRENAME_ME:
            return QStringLiteral("StoneGobletWithLavaRENAME_ME");
        case ObjectID::StonePillar: return QStringLiteral("StonePillar");
        case ObjectID::StoneThing2RENAME_ME: return QStringLiteral("StoneThing2RENAME_ME");
        case ObjectID::StoneThing3RENAME_ME: return QStringLiteral("StoneThing3RENAME_ME");
        case ObjectID::StoneThingRENAME_ME: return QStringLiteral("StoneThingRENAME_ME");
        case ObjectID::Stool: return QStringLiteral("Stool");
        case ObjectID::SwingingScythe: return QStringLiteral("SwingingScythe");
        case ObjectID::SwingingSpikeBall: return QStringLiteral("SwingingSpikeBall");
        case ObjectID::TableWithThingie: return QStringLiteral("TableWithThingie");
        case ObjectID::TarnStatue: return QStringLiteral("TarnStatue");
        case ObjectID::TheMagiciansLamp: return QStringLiteral("TheMagiciansLamp");
        case ObjectID::TheSoldiersGrave: return QStringLiteral("TheSoldiersGrave");
        case ObjectID::ThreeStones: return QStringLiteral("ThreeStones");
        case ObjectID::TinyXFeetTable: return QStringLiteral("TinyXFeetTable");
        case ObjectID::Tree: return QStringLiteral("Tree");
        case ObjectID::WHATTHEFUCKStatue: return QStringLiteral("WHATTHEFUCKStatue");
        case ObjectID::WTF: return QStringLiteral("WTF");
        case ObjectID::WallTorch: return QStringLiteral("WallTorch");
        case ObjectID::WallWithSecret: return QStringLiteral("WallWithSecret");
        case ObjectID::WallWithSecret2: return QStringLiteral("WallWithSecret2");
        case ObjectID::WallWithSpikeTrap: return QStringLiteral("WallWithSpikeTrap");
        case ObjectID::WallWriting: return QStringLiteral("WallWriting");
        case ObjectID::WallWriting2: return QStringLiteral("WallWriting2");
        case ObjectID::WallWriting3: return QStringLiteral("WallWriting3");
        case ObjectID::WaterWell: return QStringLiteral("WaterWell");
        case ObjectID::WeaponA1: return QStringLiteral("WeaponA1");
        case ObjectID::WeaponA2: return QStringLiteral("WeaponA2");
        case ObjectID::WeaponA3: return QStringLiteral("WeaponA3");
        case ObjectID::WeaponA4: return QStringLiteral("WeaponA4");
        case ObjectID::WeaponA5: return QStringLiteral("WeaponA5");
        case ObjectID::WeaponArbalest: return QStringLiteral("WeaponArbalest");
        case ObjectID::WeaponBastardSword: return QStringLiteral("WeaponBastardSword");
        case ObjectID::WeaponBattleHammer: return QStringLiteral("WeaponBattleHammer");
        case ObjectID::WeaponBow: return QStringLiteral("WeaponBow");
        case ObjectID::WeaponCrescentAxe: return QStringLiteral("WeaponCrescentAxe");
        case ObjectID::WeaponDagger: return QStringLiteral("WeaponDagger");
        case ObjectID::WeaponDarkSlayer: return QStringLiteral("WeaponDarkSlayer");
        case ObjectID::WeaponFlameSword: return QStringLiteral("WeaponFlameSword");
        case ObjectID::WeaponIceBlade: return QStringLiteral("WeaponIceBlade");
        case ObjectID::WeaponKnightSword: return QStringLiteral("WeaponKnightSword");
        case ObjectID::WeaponMoonlightSword: return QStringLiteral("WeaponMoonlightSword");
        case ObjectID::WeaponMorningStar: return QStringLiteral("WeaponMorningStar");
        case ObjectID::WeaponSeathsSword: return QStringLiteral("WeaponSeathsSword");
        case ObjectID::WeaponShiden: return QStringLiteral("WeaponShiden");
        case ObjectID::WeaponShortSword: return QStringLiteral("WeaponShortSword");
        case ObjectID::WeaponSpider: return QStringLiteral("WeaponSpider");
        case ObjectID::WeirdPillarRENAME_ME: return QStringLiteral("WeirdPillarRENAME_ME");
        case ObjectID::WhitePinkFlower: return QStringLiteral("WhitePinkFlower");
        case ObjectID::WoodenChestBody: return QStringLiteral("WoodenChestBody");
        case ObjectID::WoodenChestLid: return QStringLiteral("WoodenChestLid");
        case ObjectID::WoodenThingRENAME_ME: return QStringLiteral("WoodenThingRENAME_ME");
        case ObjectID::XFeetTable: return QStringLiteral("XFeetTable");
        default: return unknownString;
    }
}
